### ISSUE TITLE
DS#previous does not trigger DS#compute; Force DS#compute messes up DS#previous

### ISSUE THREAD

**Issue by austin-sa-wang** [js-data/js-data#100]
Calling `DS#previous` changes the dependent properties of a computed field, which would seem logical for `DS#compute` to be triggered, but it is not. To work around this issue, I call `DS#compute` after calling `DS#previous`, but that messes DS#previous.

**Comment by jmdobry** [comment]
Can you please provide more information?

- good - Your versions of Angular, js-data, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.io/org/groupsio/jsdata).

**Comment by austin-sa-wang** [comment]
Thanks for the quick response. I'll provide more detail soon.

**Comment by jmdobry** [comment]
Not seeing any activity here.

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, js-data, js-data-angular, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.io/org/groupsio/jsdata).
