### ISSUE TITLE
feat: add instance methods

### ISSUE THREAD

**Issue by kenborge** [js-data/js-data#105]
Would it be possible to add a way to configure new instance methods that are added to all resource instances. Kinda like the methods config in defineResource, but that would apply to all resources. Would be practical if one wanted to add a method to all resources, currently have to define the method on each resource that is defined

**Comment by jmdobry** [comment]
Have you tried:

```js
var store = new JSData.DS({
  methods: {
    // instance method for all resources
    foo: function () {
      return 'bar';
    }
  }
});
var User = store.defineResource({
  name: 'user',
  methods: {
    biz: function() {
      return 'baz';
    }
  }
});
var user = User.createInstance();
user.foo(); // "bar"
user.biz(): // "baz"
```

Or if you're using js-data-angular:

```js
angular.extend(DSProvider.defaults, {
  methods: {
    foo: function () {
      return 'bar';
    }
  }
});
```

```js
var User = DS.defineResource({
  name: 'user',
  methods: {
    biz: function() {
      return 'baz';
    }
  }
});
var user = User.createInstance();
user.foo(); // "bar"
user.biz(): // "baz"
```

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, js-data, js-data-angular, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.io/org/groupsio/jsdata).

**Comment by kenborge** [comment]
That was just what i wanted! Maybe the docs for Configuration should be updated since it does not include methods so couldn't figure out that this was possible

**Comment by jmdobry** [comment]
You can click the "Suggest Edits" button at the top right of every documentation page and contribute what you think is missing.
