### ISSUE TITLE
feat: Saving and validating nested resources

### ISSUE THREAD

**Issue by jmdobry** [js-data/js-data#11]
How should this be handled?

**Comment by demisx** [comment]
Back in my Rails days, I've documented how associated objects are saved in ActiveRecord depending on the relation type: https://gist.github.com/demisx/9896113. Just in case this maybe helpful.

**Comment by jmdobry** [comment]
By default any linked relations will be sent with the payload when calling `DS#save` without passing `changesOnly: true`. I'm thinking I want to add an option that says _not_ to send back certain linked relations when calling `save`.

**Comment by reppners** [comment]
+1 for having an option of wether to send the linked entities on save() or not. It should be configurable on DS Level, per ResourceDefinition and per call to save() but this kind of behavior is already the case with other options, isn't it?

**Comment by jmdobry** [comment]
Yes, it would be configurable that way.

**Comment by kentcdodds** [comment]
Would definitely like to have the ability to update only the resource and not any of the nested stuff (like `belongsTo` with a `localField`, which is my use case)

**Comment by jmdobry** [comment]
Would this be a set it and forget it thing? Would you want to be able to change this behavior at the method call level? Also, do you want this to be configurable per relation?

**Comment by kentcdodds** [comment]
I can't immediately think of a use case in my application where I would want to change the behavior after I've set it. But my intuition tells me that based on the non-predictable nature of backends it would be nice to be able to configure this at a per-method level as well

**Comment by demisx** [comment]
+1 for configuration at various levels.

**Comment by WillsB3** [comment]
+1 for configurable at various levels, if only for consistency with the other options which can be overridden at a resource or method call level.

**Comment by decafdennis** [comment]
I'm currently working on a project where we use js-data extensively (thanks @jmdobry!) and had a need for saving nested resources.

See http://pastebin.com/ffmnxwTp for the most important parts of our implementation: saveNested and copyAttributes. We are setting the behavior on the method-level (i.e. when we're doing the save) because we're saving different things at different points. Basically, copyAttributes links the required relations (if they're not linked already) and then makes a copy of the attributes, deleting/leaving out any relations you don't want to save (i.e. the ones you don't want to send to the server).

(We also had a need for adding objects into the js-data store that don't have a server-side ID yet, hence the references to "temporary" objects and IDs in the code.)

I can't be more helpful right now due to a work deadline, but I can try and contribute a patch some time over the next few weeks.

**Comment by jmdobry** [comment]
Cool I'll take a look!

**Comment by jmdobry** [comment]
In 2.0, relations are non-enumerable by default, so they _won't_ be saved. However, they can be configured to be enumerable, in which case they will be saved. Also, if you use `DS#update` instead, you get to specify exactly what is being saved. Closing for now, but I can revisit this later if necessary.
