### ISSUE TITLE
Cannot pass object for an ID - Needed for MongoDB's ObjectID keys

### ISSUE THREAD

**Issue by marklawlor** [js-data/js-data#110]
I'm trying to use js-data with an existing mongo database which uses the automatically generated [ObjectIDs](http://docs.mongodb.org/manual/reference/object-id/) as the unique _id field.  Unfortunately all read methods (eg DS#find) only allow for string or numbers and output the error "Error: "id" must be a string or a number!".  This can be easily replicated with the following example

```
var JSData = require('js-data');
var DSMongoDBAdapter = require('js-data-mongodb');

var store = new JSData.DS();
var mongoDBAdapter = new DSMongoDBAdapter('mongodb://localhost:27017/test');
store.registerAdapter('mongodb', mongoDBAdapter, { default: true });

var people = store.defineResource({
  name: 'people',
  idAttribute: '_id',
  table: 'test'
});

people.create({'name': 'john'}).then(function(person){
	// This works, person._id is an ObjectID as expected

	people.find(person._id).then(function(res){
		console.log(res);
	}, function(err){
		// [Error: "id" must be a string or a number!]
		console.log(err);
	});

	people.findAll().then(function(res){
		// [{ _id: <string hash presentation of ObjectID>, name: 'john' }]
		console.log(res);
	}, function(err){
		console.log(err);
	});
});
```

I've tried looking at the documentation for model hooks to unwrap/wrap the ObjectID but I was unable to find a solution and it seemed a rather hacky.

I'm using:
JS-Data: 1.6.3
js-data-mongodb: 0.2.2
Mongodb: 3.0.1

**Comment by jmdobry** [comment]
Hmm yeah, when I wrote js-data-mongodb I did all of my testing with a 1.x version of the node mongodb client, which does return an actual string/number for the `_id` field. That's why all the tests passed. 

Installing a 2.x version of the node mongodb client reveals that all the tests fail, due to the `_id` being an object. In fact, in 2.x create doesn't actually return the created object, so I don't even get an id back.

I personally don't use Mongo or have much experience with it, so an help would be appreciated. The mongo docs seem like a maze to me.

**Comment by jmdobry** [comment]
My database is v2.6.7, was there a breaking change in 3.x such that it returns an object instead of a string for the _id?

**Comment by jmdobry** [comment]
Does this mean I need to do `forceServerObjectId: true` in the js-data-mongodb adapter, and then always use `doc._id.toString()` or some such? Why would they write a driver that by default generates a string for `_id`, while the server would generate an `ObjectId`. Why can the driver even generate the id?

**Comment by jmdobry** [comment]
Basically, to fix this, js-data-mongodb needs to account for differences in the drivers and the id types. A little work, but shouldn't be too bad.

**Comment by marklawlor** [comment]
I looked at the issue briefly and it appears that in mongo 2.6.x [js-data-mongodb line 217](https://github.com/js-data/js-data-mongodb/blob/master/src/index.js#L217) it returns an object, not an array when using DS#Create. This is why you are not receiving a _id back for that version of mongo.

As for the ObjectID, we can check if the provided string id is a valid ObjectID hash with [ObjectId.isValid()](http://mongodb.github.io/node-mongodb-native/api-bson-generated/objectid.html#objectid-isvalid) and the adapter can handle the ObjectID creation/unwrapping

Another issue may be the peerDependancy on "mongodb": ">= 1.3.x < 2.x"

I'll look into it a bit more and try to work on a pull request

**Comment by jmdobry** [comment]
I'm going to change the peerDependency to `">= 1.3.x <= 2.x", and then each adapter method will use the correct driver method depending on whether the 1.x or 2.x driver is being used. I've already got that done.

As for the ObjectId, I have some questions, using `DSMongoDBAdapter#find(resourceConfig, id[, options])` as the example:

`DS#find` calls `DSMongoDBAdapter#find` and passes it the `id` argument that it was given. The `id` argument coming from `DS#find` will be a plain string. Is it safe for the adapter method to just pass that `id` arg straight to the driver? It doesn't need to wrap it in an ObjectId? I don't think so, because with the 2.x driver the `DSMongoDBAdapter#find` tests pass when passing just a string. Does the database convert the string to an ObjectId on its own, and then fetch the document?

Now, when the driver `find` call returns with the object, the object will either have a plain string as its `_id` field, or an ObjectId as its `_id` field. `DS#find` expects back an object whose primary key is a string, so the adapter needs to unwrap the ObjectId(if one came back) and return a string. What is the correct way to unwrap an ObjectId? From my reading it appears to be `result._id.valueOf()`. if `result._id` is already a string, then `valueOf()` is basically an identity function. If it's an ObjectId, then `valueOf()` returns the id string inside of it. Correct?

**Comment by jmdobry** [comment]
At this point, I've got some interesting results:

Driver: `1.4.35`
Server: `2.6.7`
All tests pass in `141ms`

Driver: `2.0.27`
Server: `2.6.7`
All tests pass in `1s` (why so slow?)

**Comment by jmdobry** [comment]
Closing in favor of js-data/js-data-mongodb#8
