### ISSUE TITLE
Is bluebird bundled?

### ISSUE THREAD

**Issue by Antariano** [js-data/js-data#112]
Bluebird is a top-notch promise library and I understand the sentiment of using it.
However, it adds about 70kb (30kb gzipped) to the mix. 
Is it currently bundled within the distributed files? The source is not very clear on that.

**Comment by jmdobry** [comment]
It is not. See js-data's [webpack config](https://github.com/js-data/js-data/blob/master/Gruntfile.js#L86).

Bluebird is only loaded if js-data detects that it's running in Node.js. If you're using a bundler to load js-data into your client-side app, you'll also want to add `bluebird` as an external. See [the docs](http://www.js-data.io/docs/home#use-with-webpack).

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.io/org/groupsio/jsdata).
