### ISSUE TITLE
DS.createInstance does not create computed properties

### ISSUE THREAD

**Issue by LoicMahieu** [js-data/js-data#119]
Illustrated by this plunker: http://plnkr.co/edit/MnymUvCXsGk7lSAuCPfr?p=preview
It seems that `DS.inject({ id: 1, ...})` results a instance with computed properties but `DS.createInstance({ ... })` does not.

**Comment by jmdobry** [comment]
Uhm, I think you have a typo in your plunker. You're printing `user.computed`, but I think you meant to print `user.congrats`, which works as far as I can tell. Support for this was just added in 1.8.0.
![screen shot 2015-04-15 at 9 06 27 am](https://cloud.githubusercontent.com/assets/1213510/7161887/bafed7c4-e34e-11e4-9a65-e616bc1c59a4.png)

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.io/org/groupsio/jsdata).

**Comment by LoicMahieu** [comment]
Yes indeed, `https://cdn.rawgit.com/js-data/js-data/master/dist/js-data.js` was cached on my machine in version 1.7.0... I spent more than a hour to find the issue....
Thanks for your response and big thanks for this great module!
