### ISSUE TITLE
[docs] DS.find doc don't tell that options.params exist

### ISSUE THREAD

**Issue by sinsunsan** [js-data/js-data#120]
In http://www.js-data.io/docs/dsfindall you have got a 'params' parameter

In http://www.js-data.io/docs/dsfind we can also send params in options.params 
This is useful when the ressource have a belongTo relation and we need to pass the id of the ressource parents to have an url in the form parentRessource/parentRessourceId/ressource/ressourceId

You should add an options.params line in the doc for ds.find

**Comment by jmdobry** [comment]
It actually does: 

> If `find` ends up delegating to an adapter, the `options` argument (if you passed one) will also be passed to the adapter's `find` method, so you can pass `options` to the adapter as well.

`options.params` is not used by `DS#find`, but `options.params` _is_ used by the http adapter, which is why this works. `options.params` is documented [here](https://github.com/mzabriskie/axios#request-api) if you're using js-data-http and [here](https://code.angularjs.org/1.3.12/docs/api/ng/service/$http#usage) if you're using js-data-angular.

The `params` argument of `DS#findAll` is different than `options.params`, hence why it is explicitly mentioned in the `DS#findAll` docs. `params` is first class argument for `DS#findAll` (will be used by the filter if the query is cached) while `options.params` is only incidentally useful if you're using the an http adapter.

**Comment by sinsunsan** [comment]
Ok you seem to have valid reasons, not to mention this possibility. I wanted only to tell you this with my js-data begginer point of view, as it's not easy to make suposition that we can pass this params to the http adapter.

**Comment by jmdobry** [comment]
Oh the docs...
