### ISSUE TITLE
Location Header on POST (create) resource

### ISSUE THREAD

**Issue by erikdonohoo** [js-data/js-data#125]
Some APIs don't respond with an object body on POST calls, instead returning null with a `Location` header saying where the new object has been created.  Traditionally everything after the last `/` in the url represents the new id of the model.  Is it possible to get js-data to search for this Location header in the response if it is a POST call and attempt to add an id to the model being saved?

**Comment by jmdobry** [comment]
You can access meta data of the response in the `deserialize` lifecycle hook, at which point you could properly format the data before it's sent back to the data store.

The default `deserialize` function looks like this:

```js
function (resource, data) {
  return data.data;
}
```

You could override it with something like this:

```js
function (resource, data) {
  // inspect data.headers, do something to data.data if necessary
  return data.data;
}
```

**Comment by erikdonohoo** [comment]
Great.  Thanks @jmdobry

**Comment by jmdobry** [comment]
Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [Gitter Channel](https://gitter.im/js-data/js-data) or the [mailing list](https://groups.io/org/groupsio/jsdata).
