### ISSUE TITLE
Long Term Caching

### ISSUE THREAD

**Issue by lylepratt** [js-data/js-data#126]
We are migrating an angular app from using $http with your angular-cache library to js-data. We need to be able to cache model data past app reloads (especially for mobile). There doesn't appear to be a way to configure the cache life cycle for js-data using the http adapter. Can you point me in the right direction?

**Comment by jmdobry** [comment]
@lylepratt js-data is a full-fledged in-memory data store that uses various adapters to communicate with various persistence layers. From js-data's point of view, `localStorage` is a persistence layer. js-data can communicate with `localStorage` via the [localStorage adapter](https://github.com/js-data/js-data-localstorage). Check out this [demo](https://js-data-localstorage.firebaseapp.com/).

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [Gitter Channel](https://gitter.im/js-data/js-data) or the [mailing list](https://groups.io/org/groupsio/jsdata).
