### ISSUE TITLE
Return error with type

### ISSUE THREAD

**Issue by jmas** [js-data/js-data#128]
Hello, guys.
Have question or propose. When we get data in following way:
```javascript
SomeResource.findAll()
              .then(function(items) {
                res.json(items);
              })
              .catch(function(error) {  });
```
or when we try to save data:
````javascript
SomeResource.save(1, { name: 'Andy' })
              .then(function(item) {
                res.json(item);
              })
              .catch(function(error) { });
````
Can we return `error` with type (for example `ValidationError`)?
I found that now I can't say unambiguously what `error` I get. I need this because I should return error body if this is validation error or process error in another way if otherwise.
Thanks.

**Comment by jmdobry** [comment]
On the server, js-data 1.x uses the Bluebird promise library, so you can take advantage of its error handling features to add different handlers for various error types. See [.catch](https://github.com/petkaantonov/bluebird/blob/master/API.md#catchfunction-errorclassfunction-predicate-function-handler---promise). 

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [Gitter Channel](https://gitter.im/js-data/js-data) or the [mailing list](https://groups.io/org/groupsio/jsdata).
