### ISSUE TITLE
Remove adapters

### ISSUE THREAD

**Issue by SystemParadox** [js-data/js-data#149]
Once an adapter has been added with `registerAdapter`, is it possible to remove it?

Thanks.

**Comment by jmdobry** [comment]
```js
// register
store.registerAdapter('fooHttp', new DSHttpAdapter());
// unregister
delete store.fooHttp
```

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [Gitter Channel](https://gitter.im/js-data/js-data) or the [mailing list](https://groups.io/org/groupsio/jsdata).
