### ISSUE TITLE
Is it possible to use my own classes for resources?

### ISSUE THREAD

**Issue by davidagee** [js-data/js-data#153]
I'm investigating using js-data for a production app, in order to migrate over I would need to be able to define resources which create instances of already existing classes. I need to do this because the current model uses inheritance, and also because I would prefer to use `Object.defineProperties` to create getters for computed properties over the js-data implementation.

**Comment by jmdobry** [comment]
Yes.

```js
function BaseUser() {}

var store = new JSData.DS();

Object.defineProperty(BaseUser.prototype, 'fullName', {
  get() {
    return this.firstName + ' ' + this.lastName;
  }
});

var User = store.defineResource({
  name: 'user',
  useClass: BaseUser
});

var user = User.createInstance({
  firstName: 'John',
  lastName: 'Anderson'
});

console.log(user.fullName); // "John Anderson"
```

See http://www.js-data.io/docs/dsdefaults#useclass and http://plnkr.co/edit/vNCoC8?p=preview

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [Gitter Channel](https://gitter.im/js-data/js-data) or the [mailing list](https://groups.io/org/groupsio/jsdata).

**Comment by davidagee** [comment]
Awesome, this is just what I need. The minor bug would be that the doc at http://www.js-data.io/v1.8.0/docs/dsdefineresource indicates that `useClass` is a boolean.

**Comment by jmdobry** [comment]
good catch
