### ISSUE TITLE
Bulk insert for HTTPAdapter

### ISSUE THREAD

**Issue by kyoka** [js-data/js-data#159]
What seems like a default, widely-used action is actually missing.. basically all the some logic as updateAll() but with method POST instead of PUT

**Comment by jmdobry** [comment]
Everybody thinks their way of doing things is the way everybody does things...

```js
var attrs = { verified: true };
var params = { where: { role: { '==': 'admin' } } };
var options = { method: 'POST' };

// basically all the same logic as updateAll() but with method POST instead of PUT
store.updateAll('user', attrs, params, options);
```

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [Gitter Channel](https://gitter.im/js-data/js-data) or the [mailing list](https://groups.io/org/groupsio/jsdata).

**Comment by kyoka** [comment]
thank you for clarifying, though i couldn't figure out this way on my own, since the documentation does not explain attrs params and options enough
