### ISSUE TITLE
Error with custom method that returns a Promise

### ISSUE THREAD

**Issue by leandroz** [js-data/js-data#163]
Hey, here is a Plunker with the error: http://plnkr.co/edit/36AQzJZE2LadAbZioeZV?p=preview
I put the version that works and the one that doesn't but that should work.

**Comment by jmdobry** [comment]
It's because `.then(myNewDocument.updateMyself)` is executed _before_ `myNewDocument = Document.get(document.id);`, so `myNewDocument` is not actually defined when you trying to access the `updateMyself` method.

In your working example, it works because there are now two parts:

```js
.then(function() {
  return otherDocument.updateMyself();
})
```

The `.then` is executed first and is passed the anonymous function. `return otherDocument.updateMyself();` isn't executed until _after_ `myNewDocument = Document.get(document.id);`, so that's why everything works.

Another problem you will run into is that with `.then(myNewDocument.updateMyself)`, `updateMyself` would not have been executed in the context of `myNewDocument`, but rather in the context of `window`, so your `this` reference inside of `updateMyself` would have been invalid.

**Comment by leandroz** [comment]
@jmdobry my mistake, I was trying to reproduce quickly and didn't take time to check.
 
The problem is actually what you say about the executed context, is bind to Window object instead of the instance. 
I updated the Plunker, http://plnkr.co/edit/36AQzJZE2LadAbZioeZV?p=preview to see it there.

Is this an error in my code or there is something we can do in the core of js-data to prevent this from happening?

Writing ````.then(myNewDocument.updateMyself)```` is valid since the method is returning a Promise, but i don't understand why ````this```` is on Window instead of the instance of Document.

**Comment by jmdobry** [comment]
It's not something that js-data can fix for you–it's how JavaScript works, specifically, it depends on the Promise implementation. The callback passed to `.then` is not executed in the context of the object of which the callback is a property, as in the case of `.then(myNewDocument.updateMyself)`. When the JavaScript interpreter executes `.then(myNewDocument.updateMyself)`, it passes the given callback to `.then` and binds it the window.

Some promise libraries allow you to bind the callback you pass to `.then` to a specific context as you're passing the callback to `.then`. If you just execute `myNewDocument.updateMyself()` yourself then it will correctly be executed in the context of `myNewDocument`, but when the Promise `.then` executes that callback _for_ you, it does not honor the context that `updateMyself` was originally bound to.

Here's an updated plunker that shows a way to get around it: http://plnkr.co/edit/6mCQ6u?p=preview

**Comment by leandroz** [comment]
I now understand what the problem is, thanks for the explanation @jmdobry , I search for more information, Bluebird has a Promise.bind method for setting the context, but I will stick to ````() => myNewDocument.updateMyself()```` to prevent any error.

Thanks again!
