### ISSUE TITLE
 Implementation of JSON Patch RFC6902

### ISSUE THREAD

**Issue by pdorgambide** [js-data/js-data#18]
https://tools.ietf.org/html/rfc6902
http://tools.ietf.org/html/rfc5789

**Comment by jmdobry** [comment]
I think that this particular set of functionality is out of the scope of js-data.js itself, but there is definitely room for another project that uses js-data to accomplish this. Perhaps when there's a pouchdb/couchdb adapter or GUN adapter, as those projects are already solving the CRTD problem.

Closing this issue because js-data.js itself won't implement this functionality.
