### ISSUE TITLE
Any sample with Angular2?

### ISSUE THREAD

**Issue by tapas4java** [js-data/js-data#182]
Is there any sample code with Angular2 available?

**Comment by jmdobry** [comment]
I know there are devs using js-data in their Angular2 apps, but I haven't seen any sample code.

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [Gitter Channel](https://gitter.im/js-data/js-data) or the [mailing list](https://groups.io/org/groupsio/jsdata).

**Comment by demisx** [comment]
We are migrating our app to Angular 2 and my understanding js-data and js-data-angular should be compatible as is. Some examples of usage would be really helpful.

**Comment by jmdobry** [comment]
Here is an example: https://github.com/js-data/js-data-examples/tree/master/client/angular2
