### ISSUE TITLE
Modifying Objects As They Are Retrieved

### ISSUE THREAD

**Issue by eeejayg** [js-data/js-data#193]
This is a question, not an issue.  Unable to figure this out from the docs, so perhaps you could call this an issue with the docs.  In any event, I have defined a resource such as:

DS.defineResource({
  name: 'itinerary',
  endpoint: '/USD',
  basePath: 'http://173.22.101.251:8080/itineraries'
});

As each object comes in from the remote server, I want to decorate the object with additional properties before it goes into the data store.  How do I do that?

**Comment by jmdobry** [comment]
Here's my answer to your question on the mailing list: 

> Use the beforeInject or afterInject hooks: [model-lifecycle#section-ds-inject](http://www.js-data.io/docs/model-lifecycle#section-ds-inject)

You can also use the `deserialize` hook: http://www.js-data.io/docs/dshttpadapter#default-settings

You can also add a response interceptor to $http.

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [Gitter Channel](https://gitter.im/js-data/js-data) or the [mailing list](https://groups.io/org/groupsio/jsdata).
