### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by eeejayg** [js-data/js-data#194]
How do you turn off the info logs.  Each time a remote server call is made to getting something not in cache, it does a log to console.info.

Thank you.

**Comment by jmdobry** [comment]
Set the `log` property of the http adapter to `false`: http://www.js-data.io/docs/dshttpadapter#section-setting-defaults

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [Gitter Channel](https://gitter.im/js-data/js-data) or the [mailing list](https://groups.io/org/groupsio/jsdata).
