### ISSUE TITLE
support for query parametrs for post(create)

### ISSUE THREAD

**Issue by sanjayjagadish** [js-data/js-data#202]
We are having a post which takes query parameters. Can we pass query parameters to post

**Comment by jmdobry** [comment]
`DS.create('post', { content: 'foo' }, { params: { beep: 'boop' } });`

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [Gitter Channel](https://gitter.im/js-data/js-data) or the [mailing list](https://groups.io/org/groupsio/jsdata).

**Comment by sanjayjagadish** [comment]
Thanks Jason. It worked. Couldnt find this syntax on js-data docs. Appreciate your quick response
