### ISSUE TITLE
Local storage issue after refresh

### ISSUE THREAD

**Issue by sanjayjagadish** [js-data/js-data#213]
Hi Jason,

We came across one issue while using localStorage adapter. When we do page refresh, we are unable to retrieve data(js-data loses track of the data), even though the data is present in local storage. Can you please advice on this issue or are we we missing any configuration.

Thanks,
Sanjay

**Comment by jmdobry** [comment]
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

**Comment by sanjayjagadish** [comment]
We are using the below versions.
"angular": "1.3.15",
"js-data-angular": "2.4.0",
"js-data": "1.8.0",
"js-data-localstorage": "1.1.1",

To explain a bit more on issue. say I have injected a user object into localstorage by 
UserModel.create(User, {
					adapter: 'localstorage'
				});

Then the page is refreshed. and I try 
UserModel.get(data, {
					adapter: 'localstorage'
				});

I get undefined rather than getting the User data. But the data still exists in the localstorage.

**Comment by jmdobry** [comment]
The docs' explanation of `DS#get`:

> Synchronously return the item with the given id from the store.
>
> Returns undefined if the item is not in the store.

When you refresh the page everything in memory gets wiped, including the in-memory store. If you want to retrieve data from a persistence layer via an adapter then you need to use one of the async methods, e.g. `DS#find` or `DS#findAll`.

```javascript
UserModel.find(1, {
  adapter: 'localstorage'
}).then(...);

UserModel.findAll(null, {
  adapter: 'localstorage'
}).then(...);
```

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:

Otherwise support is done via the [Gitter Channel](https://gitter.im/js-data/js-data) or the [mailing list](https://groups.io/org/groupsio/jsdata).
