### ISSUE TITLE
 DS#findAll - Smart arguments

### ISSUE THREAD

**Issue by crobinson42** [js-data/js-data#241]
It is typical to use Resource#findAll([params][, options]) without the [params] argument because the intention is to get the entire list for that Resource. The second is this is very common to be used with { bypassCache: true }.

The quirk when completing this is *Resource#findAll( null , { bypassCache: true } )*

I propose DS#findAll uses logic that iterates the keys of the first argument and any of those keys match a config key, it assumes the 1st argument is a config/options object.

**Comment by antoinebrault** [comment]
What if you have a param key that is equal to a config key? It really just make things more complicated and error prone IMO.

**Comment by jmdobry** [comment]
I agree, which is why I've been avoiding this issue :stuck_out_tongue_winking_eye: I have two issues with this: 

1. I don't like overloaded method signatures.
1. The implementation would suck, because now we'd have to maintain a list of all possible config options across JSData and all the adapters. That's hundreds of options. The array of strings alone would add a few kilobytes to the minified build.

@crobinson42 Perhaps to avoid the annoyance of passing `null` when you don't have any `params` you want to pass, maybe you could do the following:

```js
store.findAll.before(function (resourceName, params, options) {
  var paramsIsConfig = false
  params = params || {}
  for (var key in params) {
    paramsIsConfig = paramsIsConfig || this.defaults[key] !== undefined 
  }
  return !options && paramsIsConfig ? [resourceName, null, params] : [resourceName, params, options] 
})
```

**Comment by crobinson42** [comment]
Thanks for the code snippet and review.
