### ISSUE TITLE
Filter behaviour changed unexpectedly

### ISSUE THREAD

**Issue by rbao** [js-data/js-data#255]
First of all, thanks for a great library!

Here is the code (plunker included at bottom)
```
var store = new JSData.DS();

var Post = store.defineResource('post');
var User = store.defineResource('user');

var post = { id: 1 };
var user = { id: 1 };

var post = Post.inject(post);
var user = User.inject(user);

post.author = user;

console.log("All Post: ", Post.getAll());
console.log("All User: ", User.getAll());
console.log("Filtered: ", Post.filter({ author: user}));
```

The above code when run in 2.3.0 outputs the following
```
All Post:  [Post]
All User:  [User]
Filtered:  [Post]
```
This is as expected

However the above code when run in  > 2.3.0 outputs the following
```
All Post:  [Post]
All User:  [User]
Filtered:  []
```
Note everything is filtered out where it suppose to return a single post with the specified author.

I did not see anything regarding filter been changed in the CHANGELOG so I am wondering why this behaviour has changed? Am I doing something wrong?

[plunker](http://plnkr.co/edit/4XPtjK0WvfsqH0uHrXeF?p=preview)

**Comment by jmdobry** [comment]
```js
Post.filter({ author: user })
```

I'm surprised this ever worked for you, as I never implemented it and it's never been documented as a feature. If it worked it was by accident.

Typically what recommend is that you do `Post.filter({ authorId: user.id })`, especially if you're going to pass those same parameters to `DS#findAll` because the adapters aren't going to have any idea what to do with `{ author: user }`. With the HTTP adapter, those params will throw up on your querystring.

```js
Post.filter({ authorId: user.id })
```

is just shorthand for:

```js
Post.filter({
  where: {
    authorId: {
      '==': user.id
    }
  }
})
```

**Comment by rbao** [comment]
got it, thanks
