### ISSUE TITLE
#update and #destroy should throw if the resource to be updated cannot be found

### ISSUE THREAD

**Issue by phparkle** [js-data/js-data#256]
This would have to be implemented in each adapter but we could talk about it here in general. This is in line with the idea that a PUT or DELETE to a REST API should respond with 404 if the resource cannot be found.

**Comment by jmdobry** [comment]
I think I agree. On the flip side, I no longer believe `DS#find` should throw if the item can't be found.

**Comment by jmdobry** [comment]
Also, I think some of the adapters might already throw on update/delete when the item doesn't exist.

**Comment by jmdobry** [comment]
I decided that I think it's okay for the adapter to throw when attempting to update something that doesn't exist. However, I think throwing when destroying something that doesn't exist is too much.

With v3, there's no longer risk of losing context either because passing `raw: true` will cause adapters to instead return a result object that can be inspected. For example, passing `raw: true` and destroying a row that doesn't exist should return something like:

```
{
  data: undefined, // nothing was destroyed, so no id to reference
  deleted: 0 // count of how many items were deleted, in this case 0
}
```

So here your `destroy()` call won't throw, as the intent has been accomplished (item doesn't exist), but if you're still concerned about whether the item was destroyed _in that operation_ you can inspect the result object.

**Comment by jmdobry** [comment]
Implemented in v3.
