### ISSUE TITLE
PostgreSQL functions 

### ISSUE THREAD

**Issue by andrejkaurin** [js-data/js-data#268]
Does js-data (DSSqlAdapter) is able to work with PostgreSQL functions? 

I general, is there option to just execute SQL query? "SELECT myFunc(  '101');"

**Comment by jmdobry** [comment]
Yes. js-data-sql uses [Knex.js](http://knexjs.org/) under the hood. Once you have an instance of `DSSqlAdapter`, then you can access the underlying knex object at `DSSqlAdapter#query`. The Knex documentation has more on what Knex can do.

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is handled via the [Slack Channel](https://slack.js-data.io) or the [Mailing list](https://groups.io/org/groupsio/jsdata).
