### ISSUE TITLE
Supported operators for DSSqlAdapter

### ISSUE THREAD

**Issue by andrejkaurin** [js-data/js-data#270]
Which operators are supported by DSSqlAdapter. In Example "LIKE" is supported and "ILIKE" (specific for PostgreSQL) is not.
I am trying to do case insensitive compare (search) but this is not working:

where: { 'name' : {'ilike' : 'An%'}} 

however this works

where: { 'name' : {'like' : 'An%'}}

**Comment by jmdobry** [comment]
You can see what operators are supported by js-data-sql [here](https://github.com/js-data/js-data-sql/blob/master/src/index.js#L338). Also, if this were an issue with js-data-sql, then the issue would belong in https://github.com/js-data/js-data-sql/issues.

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of js-data, js-data-sql, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is handled via the [Slack Channel](https://slack.js-data.io) or the [Mailing list](https://groups.io/org/groupsio/jsdata).
