### ISSUE TITLE
Cannot use #createInstance to push to a hasMany relation.

### ISSUE THREAD

**Issue by dnd** [js-data/js-data#271]
I have a resource `transaction` that hasMany `transactionItems`. I wanted to add an empty transactionItem to the transaction, but nothing seems to happen. There are no errors, but the items array is empty after the operation. I can't find anything in the docs to indicate what exactly the behavior should be, but it feels like something is wrong. Either an error should be thrown, or the new instance added, not just silent failure.

```javascript
var transaction = Transaction.createInstance(); // Transaction {}
transaction.items.push(TransactionItem.createInstance()); // 1
transaction.items // []
```

**Comment by jmdobry** [comment]
> Cannot use #createInstance to push to a hasMany relation

That is correct. If `linkRelations` is set to `true` (which is the default), then the field specified by `localField` in your relation definition is a [property accessor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get), which means you're not supposed to try and modify it. Automatic relation linking only works for data that has been injected into the datastore, which means it only works for items that have a primary key. e.g.

```js
item.transaction === Transaction.get(item.transactionId); // true
assert.deepEqual(transaction.items, Item.findAll({ transactionId: transaction.id })); // true

transaction; // { id: 1 }
transaction.items; // [ ]
var item = Item.inject({ id: 2, transactionId: 1 }); // { id: 2, transactionId: 1 }
transaction.items; // [{ id: 2, transactionId: 1 }]
transaction.items[0] === item; // true
```
-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of js-data, js-data-sql, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

__Otherwise support is handled via the [Slack Channel](https://slack.js-data.io) or the [Mailing list](https://groups.io/org/groupsio/jsdata).__
