### ISSUE TITLE
Question: Access to Store calling method name in Adapter deserialize method

### ISSUE THREAD

**Issue by raveclassic** [js-data/js-data#274]
Hi!

I have an API endpoint set up that it answers either an array if no query params passed or an object if an id is passed:
```
GET /user - {data: Array; status: Number}
GET /user/1 - {data: Object; status: Number}
```

DS uses different methods to fetch collections and objects: `findAll` and `find` respectively.
How can I access calling method name without rewriting default DS? I looked into the sources and it seems that store uses an `id` to create path in `getPath` before passing `resourceConfig` and `data` when resolving promise.

Can It be possible to somehow attach this info to `resourceConfig` to use conditional deserialization?
PS. It is undesirable to check response type like `Array.isArray`, but preferable to pass some meta info to `deserialize`.

TIA

**Comment by jmdobry** [comment]
Currently, there is no way to access the calling method name. However, if you're wanting some "conditional" deserialization, instead of defining a single `deserialize` hook, you could define the `afterFind` and `afterFindAll` hooks.

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of js-data, js-data-sql, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

__Otherwise support is handled via the [Slack Channel](https://slack.js-data.io) or the [Mailing list](https://groups.io/org/groupsio/jsdata).__
