### ISSUE TITLE
Self-Referencing entity and belongsTo entity

### ISSUE THREAD

**Issue by andrejkaurin** [js-data/js-data#275]
```javascript
var Note = db.store.defineResource({
  name: 'note', 
  table: 'note', 
  relations: {
    belongsTo: {
      user: {
        localField: 'user',
        localKey: 'user_id',
        parent: true
      }
    },
    hasMany: {
      note: {
        localField: 'notes',
        foreignKey: 'parent_id'
      }
    }
  }
});
```

When retrieving I am calling 

Note.findAll(query, { with: ['user', 'note'] })

However, every item list contains "user" property but list of child notes (for each note) does not have "user" property. This is normal of course but is there any option to force relation to return always?

**Comment by jmdobry** [comment]
You could do something like this: `Note.findAll(query, { with: ['user', 'note', 'note.user'] })`, but if you're using the http adapter, then it's really up to you to get your server to respond with what you want. But, if you're also using js-data on the server, then all the other adapters (not http), know how to handle `Note.findAll(query, { with: ['user', 'note', 'note.user'] })`

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of js-data, js-data-sql, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

__Otherwise support is handled via the [Slack Channel](https://slack.js-data.io) or the [Mailing list](https://groups.io/org/groupsio/jsdata).__
