### ISSUE TITLE
Matching relationship objects

### ISSUE THREAD

**Issue by mustela** [js-data/js-data#291]
Hi there!

I have the following resources:

```javascript
function UserBackendResource(DS) {
  return DS.defineResource({
    changesOnly: true,
    name: 'user',
    endpoint: 'users',
    hasMany: [{
        organization: {
            localField: 'organizations'
        }
      }]
});

function OrganizationResource(DS) {
    return DS.defineResource({
      changesOnly: true,
      name: 'organization',
      endpoint: 'organizations',
      belongsTo: {
          organizationType: {
              // localField is for linking relations
              localField: 'type',
              // foreignKey is the "join" field
              // the name of the field on a profile that points to its parent user
              foreignKey: 'organization_type_id'
          }
      }
    });
}


function OrganizationTypeResource(DS) {
    return DS.defineResource({
      changesOnly: true,
      name: 'organizationType',
      endpoint: 'organization-types',
      hasMany: {
          organization: {
              // localField is for linking relations
              localField: 'organizations',
              // foreignKey is the "join" field
              // the name of the field on a profile that points to its parent user
              foreignKey: 'organization_type_id'
          }
      },
    });
}
```

And this is the response when I `GET` to `/user/:id`

```json
{ "avatar_url" : "https://www.gravatar.com/avatar/abc4ad3d452feb99cd928f28ace8c1a40",
  "email" : "pepe@gmail.com",
  "first_name" : "Pepe",
  "full_name" : "Pepe Jon",
  "id" : "4ec61ea9-Jon-4a7a-a127-7c1313272d4c",
  "last_name" : "Jankowski",
  "organizations" : [ { "created_at" : "2016-01-06T19:23:02.052Z",
        "id" : "ffee2b15-caaf-480d-b4be-169cbc07f447",
        "name" : "My org",
        "organization_type_id" : "6383e25a-91a1-4a89-8c07-bda1c288283a"
      } ]
}
```

And this is the response of `GET` to `/organization-types` 

```json
[ { 
    "id" : "6383e25a-91a1-4a89-8c07-bda1c288283a",
    "name" : "Vendor"
  },
  { 
    "id" : "c02c8316-ba14-4cfa-9d3a-e774e557245b",
    "name" : "Research Firm"
  }
]
```

But when I do `someUser.organizations[0].type`, it is just empty. Shouldn't it "join" the organizatons with the types?

Thanks!

**Comment by jmdobry** [comment]
Your resources are configured incorrectly. The `belongsTo` and `hasMany` options need to be nested under a `relations` option. Here's a plunker with your corrected code: http://plnkr.co/edit/zTZpcj?p=preview

-----

The issue tracker isn't for support questions. Closing because I’m not sure this is a bug, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of js-data, js-data-angular, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

__Otherwise support is handled via [Stack Overflow](http://stackoverflow.com/questions/tagged/jsdata), [Slack chat](https://slack.js-data.io) or the [Mailing List](https://groups.io/org/groupsio/jsdata).__

**Comment by mustela** [comment]
Damn it. Sorry too many tries...
