### ISSUE TITLE
Retrieve from more than 2 tables 

### ISSUE THREAD

**Issue by georgi-kovachev** [js-data/js-data#317]
I would like to retrieve for this sql.
select * from inv_charge, account where inv_charge.acct_level_1 =account.account_no and account.vendor = 'AT&T'

Note: account.account_no and inv_charge.acct_level_1 are not primary ids, they are just string.

How can I define Resource and run the query?

**Comment by jmdobry** [comment]
Closing, since you [already asked this](http://stackoverflow.com/questions/36404089/js-data-joining-tables-without-using-prmary-ids) on Stack Overflow (which is the best place for support questions).

--- 

Closing because I’m not sure this is a bug. If you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of js-data, js-data-angular, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

__Otherwise support is handled via [Stack Overflow](http://stackoverflow.com/questions/tagged/jsdata), [Slack chat](https://slack.js-data.io) or the [Mailing List](https://groups.io/org/groupsio/jsdata).__
