### ISSUE TITLE
Import error in TypeScript

### ISSUE THREAD

**Issue by zakjan** [js-data/js-data#328]
`import {DataStore} from 'js-data'` throws an error `Cannot find module 'js-data'` in TypeScript.

I believe it is because of missing `declare module 'js-data'` in the d.ts file. There is the same issue with `js-data-http`, `js-data-adapter` and others.

js-data 3.0.0-beta.5
TypeScript 1.8.10

**Comment by jmdobry** [comment]
I will take a look.

**Comment by jmdobry** [comment]
Here's an example that uses Angular 2 + TypeScript + js-data v3. TypeScript is able to automatically pick up the JSData definitions files. 

https://github.com/js-data/js-data-examples/tree/master/client/angular2

**Comment by zakjan** [comment]
Ok, I've found my problem. Currently I use JSPM and Gulp build scripts, and I needed to use `typings install --save file:jspm_packages/npm/js-data@3.0.0-beta.6/typings.json` command to make the typings globally available.

**Comment by zakjan** [comment]
See this discussion https://github.com/Microsoft/TypeScript/issues/6012

**Comment by jmdobry** [comment]
So, when using JSPM, do `typings install --save file:jspm_packages/npm/js-data@3.0.0-beta.7/typings.json`

Otherwise, you don't have to do anything, because TypeScript will automatically pickup JSData's definitions file. JSData's current use of `"typings": "dist/js-data.d.ts"` in `package.json` is fully in line with the new TypeScript definition announcement. Hopefully JSPM can get on board.
