### ISSUE TITLE
lastModified vs lastSaved: Why not consistent?

### ISSUE THREAD

**Issue by benshell** [js-data/js-data#348]
I'm unclear why `lastModified` and `lastSaved` work differently. `lastModified` support an optional ID and returns `resource.collectionModified` if the ID was not passed. `lastSaved` does not, and ends up adding an `undefined` record, set to zero. The docs don't mention this difference, and actually say `Return the timestamp of the last time either the collection for resourceName or ...`. The header for this docs page also indicates an optional ID: `DS#lastSaved(resourceName[, id])`, although down below it says `DS#lastSaved(resourceName, id)`:
http://www.js-data.io/docs/dslastsaved

I'm happy to help--either to update the docs, or add this functionality (which I could use!). What are your thoughts?

**Comment by jmdobry** [comment]
I just updated the docs to reflect current behavior. If you want to submit a PR that adds support for `collectionSaved` (see the links below on `collectionModified`), that's fine.

https://github.com/js-data/js-data/blob/v2/src/datastore/sync_methods/defineResource.js#L273
https://github.com/js-data/js-data/blob/v2/src/datastore/sync_methods/defineResource.js#L388
https://github.com/js-data/js-data/blob/v2/src/datastore/sync_methods/index.js#L381

**Comment by jmdobry** [comment]
Closing because I’m not sure this is a bug. If you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of js-data, js-data-angular, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

__Otherwise support is handled via [Stack Overflow](http://stackoverflow.com/questions/tagged/jsdata), [Slack chat](https://slack.js-data.io) or the [Mailing List](https://groups.io/org/groupsio/jsdata).__
