### ISSUE TITLE
Records created using store.createRecord do not get updated when saved.

### ISSUE THREAD

**Issue by nvahalik** [js-data/js-data#360]
```
var a = store.createRecord('student')
a.save()
 .then((b) => {
   a === b // false, this is the bug
   b.foo = 'bar'
   return b.save()
 })
 .then((c) => {
   b === c // oh hey, but this works!
 })
 
```

Or see this Plnkr: http://plnkr.co/8Pox2KOI9Zyb47H0iwN0

**Comment by jmdobry** [comment]
Okay, so I took a look at this again, and here's the problem. `a` is a record, but it has not yet been added to the store. During the first `save` operation, the result that comes back from the adapter is added to the store. The record that is added to the store has the newly generated primary key, and is a different object in memory than the original record on which `.save` was called. I can't get around this.

Here's the logic when calling `Record#save`:

Is the record already in the store?

* No - the result of `save` will be a reference to the record received back from the adapter, which was also added to the store
* Yes - the result of `save` will be a reference to the same object you called `save` on

_If you passed `raw: true`, then obviously the return value will be a different object. _

**Comment by nvahalik** [comment]
The problem is that this object shows up in relationships that are already loaded. It's showing up in views, but isn't the fully saved object:

1. Load object that had object 2 relationship. 
2. Run createRecord and pass in the relevant key. 
3. Item shows up in related ng-repeat. 
4. Save object. 
5.  Unsaved record still shows. 

This feels like a bug.

**Comment by jmdobry** [comment]
The current architecture of JSData will not allow this to work. The core reason is that the store only allows records that have primary keys to be added to the store. I can easily change things so that the record calling save will be updated with the result coming from the adapter, but JSData cannot change which record your reference is pointing to. JSData can't know everywhere that you have a reference and change what your reference is pointing to, it just doesn't work that way. I might be able to update links for related records that _are_ in the store, but not for anything outside of the store.

```
var student = store.createRecord('student')
student.save().then((_student) => {
  student === _student // false, the current architecture of JSData does not allow this to be true
  _student === store.get('student', _student.id) // true
  student === store.get('student', _student.id) // false
})
```

```
var student = store.get('student', 1234)
student.foo = 'bar'
student.save().then((_student) => {
  student === _student // true, this works
  _student === store.get('student', _student.id) // true
})
```

If I can find a way to make it so the store can hold unsaved records (records that don't have a primary key), then maybe I can make this work.

**Comment by nvahalik** [comment]
Added this plnkr which shows another issue: http://plnkr.co/edit/KwOiE7. In this demo, a Record created with createRecord that includes data to tie it to a related Record that is already loaded shows up in related Record. In the example, when you run create record, the ng-repeat for the hasMany relationship shows the newly created record. Though, no matter how many times you run createRecord, no more are being created.

**Comment by jmdobry** [comment]
@nvahalik Can you try `3.0.0-beta.10` and see how it works for you?

**Comment by jmdobry** [comment]
I fiddling with your plunker, switching to `3.0.0-beta.10`, and it appeared to work. I'll mark this bug as fixed.

Comment here if it doesn't work for you.
