### ISSUE TITLE
Resource.pendingQueries on server causes unexpected behaviour [v2.9]

### ISSUE THREAD

**Issue by robertdp** [js-data/js-data#364]
`Resource.pendingQueries` caches unresolved requests to `find()` and `findAll()`, which have resulted in a whole mess of problems trying to use js-data on the server.

If two distinct requests are made for the same record, by _anyone_, at roughly the same time, even if `find()` is called with different options, then js-data uses the cached first promise in `pendingQueries`. All other requests for the same record are ignored, because js-data (implicitly and wrongly) returns the pending request instead making a new request.

And this behaviour is not configurable.

Edit: My current workaround is to reimplement and override `find()` and `findAll()` elsewhere in the project, removing all references to `resource.pendingQueries`.

Edit 2: Here are the overridden methods, with _all_ server-breaking caching removed: https://gist.github.com/robertdp/b1dcaf7f67288c107c2104cb4635e9db

**Comment by jmdobry** [comment]
I should note that this is already fixed in v3

**Comment by eldridge** [comment]
I'm not sure 14be7e5 does the right thing here.  When I set usePendingFind/usePendingFall to false on the server, all of my lookups resolve with undefined.  It looks like nothing gets sent to the adapter at all.  Moreover, it looks like queryHash does not respect the with parameter, which ends up causing the related queries to not be sent to the database backend (with the SQL adapter, anyways -- perhaps other adapters handle that differently).

It looks like maybe the check for usePendingFindAll should not except the entire block, just the bits that inject/return things into/from pendingQueries.  I'm testing a modification now that just bypasses those checks instead of excepting that entire block.  If all goes well (and I'm not misunderstanding how the pending queries work), I'll follow up with a PR.
