### ISSUE TITLE
Defining non-entity endpoints

### ISSUE THREAD

**Issue by demisx** [js-data/js-data#37]
What would be the right approach to define a non-entity end point in js-data?

Something like this:

```bash
GET /projects/:projectId/search?q=some+query&facet1=value1&face2=value2...
```

Do I still need to define `search` as a resource (e.g. `var Search = store.defineResource('search')`);? Or is there a better way?

**Comment by jmdobry** [comment]
You can either add a custom static method to the resource definition that does what you want, or wait for "actions" (original issue [here](https://github.com/jmdobry/angular-data/issues/261))  to be implemented.

```js
var User = DS.defineResource('user');
User.search = function (myArg) {
  // do my thing
};
```

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.io/org/groupsio/jsdata).
