### ISSUE TITLE
Validation Behaviour & Guidelines (3.0) (question)

### ISSUE THREAD

**Issue by pik** [js-data/js-data#378]
From my understanding the default behavior of JS-Data is to validate on `set`. This is unusual and if possible it would be great to have some guidelines for how this should be applied (and the use cases for it - documentation on `validation` (3.0) is also missing at the moment). 

Toy schema for reference <span id="a1">[below](#f1)</span>. Suppose as below I have defined `minLength` and `maxLength` on `firstName` now if the name is being sourced from user input directly something like `person.firstName = 'j'` will raise an error - is this tangibly useful? Is there an example somewhere of JS-Data glueing to input elements / error message handling ? 

The possible use case I see is that the input element code would have to specify a `try .. catch` in it's setter (and display a form / input as `invalid` until the property has been successfully set on the object), in which case the `firstName` would not be written to the model until it could validate min/max length. 

Also there is a particularity to how this `set` behaviour will work when using nested fields (nice up-side to jsonschema though that they can be validated). So `emergencyContact` below allows 'null' so that it may be unset, but then expects to be filled in with required fields. That means that an input which attempts to set a valid `contactNumber` on the `person` instance will fail - and the entire form needs to be synced at once. 

The later might look like this -- 

``` es6
try {
  person.emergencyContact = this.emergencyContact
} catch(e) {
  e.errors.forEach((error) => {
    this.$[error.path.split('.')[1]] && (this.$[error.path.split('.')[1]].invalid = true);
  })
  return
}
```

but being explicit in each field set is probably less appealing than `validate()` - since the later could work generically and not need to be duplicated: 

``` es6
save(person) { 
  try { 
    person.validate() 
  } catch(e) {
    e.errors.forEach((error) => {
      this.$[error.path.split('.')[1]] && (this.$[error.path.split('.')[1]].invalid = true);
    })
    return 
  }
  person.save()
}
```

An interesting point @jmdobry  brought up on slack was the use of a viewModel - in case of the later you could consider an interface that looks something like:

``` es6
class Ephemeral {
  constructor(obj) {
    /*  Wraps a JS-Data model and proxies it's properties */
  }
  sync() {
    /* syncs proxied properties to underlying JS-Data model */ 
  }
}
```

I am inclined to think that in such a case the validation behaviour would like highly similar to the `try .. validate() catch {..} save()` though only it would be `try .. sync() catch {..} save()`. Not sure over-all how many advantages there are to separating view and data-models, but I suppose a lot of the 'heaviness' (e.g. changeTracking per `set` rather than per 'persist') comes from the JS-Data models being used on the back-end as well? 

<b id="f1"></b>

``` es6
  const EmergencyContactSchema = new Schema({
   'properties': {
      'contactName': {'type': 'string'},
      'contactNumber': {'type': 'string'},
      'relationship': {'type': 'string'}
    },
    'required': ['contactName','contactNumber','relationship'],
    'type': ['object', 'null']
  })

  const PersonSchema = new Schema({
    $schema: 'http://json-schema.org/draft-04/schema#',
    title: 'Person',
    description: 'Schema for a Person Record.',
    type: 'object',
    properties: {
      firstName: { type: 'string', default: '', minLength: 2, maxLength: 32 },
      lastName: { type: 'string', default: '' },
      emergencyContact: EmergencyContactSchema,
    }
  })

  const Person = store.defineMapper('person', {
    endpoint: 'person/',
    schema: PersonSchema
  })
```

 [↩](#a1)

**Comment by jmdobry** [comment]
Some good points raised here. Let me think on this, anyone else is welcome to chime in.

**Comment by billdybas** [comment]
I am also eagerly awaiting v3 documentation for validation. I haven't analyzed the code enough to know the exact behavior of validation, but these are my thoughts:

The whole point of validating models is to enforce structure to your data, so that when it's referenced later, it's in the format you expect. So the validation should act as a guard on the persistence layer making sure any data entering is correct. 

So here, when is the change actually committed to the persistence layer? If the commit is immediate, having validation on something like `person.emergencyContact = this.emergencyContact` makes sense, albeit different from other ORMs. But if the changes aren't actually persisted until `save()` is called, then it seems that validation on `set` is a bit too much. Having to account for exceptions every time you change a property will grow old very quickly. 

The other thing to consider is who should enforce the validation: the ORM or the ORM user? Should I have to call `validate`, or can I expect it to happen automatically on other methods?

Let's look at some examples:
- [Django](https://docs.djangoproject.com/en/1.10/ref/models/instances/#validating-objects) doesn't validate before save (and requires the user to do so similar to the `try` `catch` example above, but gives adequate customizable [form validation](https://docs.djangoproject.com/en/1.10/ref/forms/validation/#form-and-field-validation) beforehand so that this isn't a problem.
- [Mongoose](http://mongoosejs.com/docs/validation.html) validates before save.
- Rails' [Active Record](http://guides.rubyonrails.org/active_record_validations.html) validates before save. It's interesting that it has operations that will throw exceptions and some that won't. 

The ORM that I would want to use is one that has my back and reduces my memory load, so that I don't have to remember a checklist of things to do any time I want to work with my data. It should work out of the box and not require me to build abstractions on top of its core functionality in order for it to be usable and my code maintainable.

**Comment by jmdobry** [comment]
JSData v3 currently calls `validate` for you in the `beforeCreate`, `beforeCreateMany`, `beforeUpdate`, `beforeUpdateMany` and `beforeUpdateAll` hooks. Since those hooks run inside a promise chain, a validation error will kick the code execution over onto the `catch` track.

```js
person.save().then((person) => {
  // success
}, (err) =< {
  // failure

  // if it's a validation error:
  console.log(err.errors); // [{...}, {...}, ...]
});
```

The `options` you pass to `create`, `createMany`, `update`, `updateMany`, `updateAll`, and `save` will also be passed to `validate`. You can force it to skip validation on save by passing `noValidate: true`, e.g.:

```js
store.create('person', { name: 'John' }, { noValidate: true }).then((person) => {
  // success
}, (err) => {
  // failure
  // there still might be a failure, but it won't be a validation error
});
```

As far as validation on set goes (e.g. `person.name = 1234`), it is possible to disable it, but currently can only be disabled per-Record instance, and it defaults to validating on set.

It sounds like you would appreciate a Mapper-wide setting that disables validation on set of all Record instances associated with a Mapper, correct?

**Comment by pik** [comment]
> So here, when is the change actually committed to the persistence layer? If the commit is immediate, having validation on something like person.emergencyContact = this.emergencyContact makes sense, albeit different from other ORMs. But if the changes aren't actually persisted until save() is called, then it seems that validation on set is a bit too much. Having to account for exceptions every time you change a property will grow old very quickly.

I tend to agree with this as I was saying in my previous post. It's generally easier to deal with `.validate()` and display errors then per field settings, the setter behavior might make a lot more sense for users running JS-Data + node in the backend.  For front-end the only exception to this I could think of would be something like <sup id="a1">[this below](#f1)</sup> - where an input element's validated state is updated in real time but it seems to be in that case one could always provide the opposite interface e.g.

```es6
record.set(fieldName, value, { noValidate: false })
```

Since for the `validate()` on `set()` property to be useful there almost always would need to be a try/catch or at least so it seems to me. Note that atm, `set()` cannot take a `noValidate` option and always validates..

> Django doesn't validate before save 

Django doesn't validate before save but it provides a framework for validating which makes it very easy -- so something like this is probably not uncommon;
```python
class BaseModel(models.Model):
    def save(self, *args, **kwargs):
        """Always call #full_clean before saving"""
        self.full_clean()
        super(BaseModel, self).save(*args, **kwargs)
```
Also it is a point that Django differs significantly from Rails in that it tends to use DB Level constraints more so (e.g. ForeignKeys) which Rails has historically not used (support has only come very recently, somewhere ~4.20ish).

> The ORM that I would want to use is one that has my back and reduces my memory load, so that I don't have to remember a checklist of things to do any time I want to work with my data. It should work out of the box and not require me to build abstractions on top of its core functionality in order for it to be usable and my code maintainable.

Very much agree with this and common patterns that aren't the default should be very easy to obtain. 


<b id="f1">http://plnkr.co/edit/zldmOTw2mV7WjnxogqA9?p=preview</b>
```es6
  let record = TestMapper.createRecord()
  let fieldName = 'validatedField'
  let input = document.getElementById('validating-input')
  input.addEventListener('keyup', function(fieldName, event) {
    console.log(event.target.value)
    let target = event.target
    try {
      record[fieldName] = target.value
      target.classList.remove('invalid')
    } catch (e) {
      console.log('error', e)
      target.classList.add('invalid')
    }
  }.bind(record, fieldName))
```
[↩](#a1)

**Comment by billdybas** [comment]
> It sounds like you would appreciate a Mapper-wide setting that disables validation on set of all Record instances associated with a Mapper, correct?

👍  Yes, that would be great!

There are valid use cases for both validating on set and waiting to batch the validation errors (through calling `validate` or on save), so I think having this configurable seems like the best option. I could see this being configurable both on individual Mappers and through `mapperDefaults`.

**Comment by jmdobry** [comment]
> I could see this being configurable both on individual Mappers and through `mapperDefaults`

Yes, that's exactly how it would work

**Comment by jmdobry** [comment]
Until I implement the configuration option, here's how you would do it now:

```js
class BaseRecord extends JSData.Record {
  constructor(props, opts) {
    super(props, opts);
    this._set('noValidate', true);
  }
}

store.defineMapper('user', {
  recordClass: BaseRecord,
  schema: {
    properties: {
      age: { type: 'number' }
    }
  }
});
const user = store.createRecord('user');
user.age = 'foo'; // no error is thrown
```

**Comment by jmdobry** [comment]
The configuration option was implemented a while back, here's how it works:

```js
// LOTS OF VALIDATION
store.defineMapper('user', {
  schema: {
    properties: {
      age: { type: 'number' }
    }
  }
});

// NO VALIDATION ON PROPERTY SETTERS
store.defineMapper('post', {
  // Disable validation on property setters
  validateOnSet: false,
  schema: {
    properties: {
      title: { type: 'string' }
    }
  }
});

// NO VALIDATION AT ALL
store.defineMapper('comment', {
  // Disable validation on property setters
  validateOnSet: false,
  // Skip validation in createRecord, beforeCreate, beforeCreateMany, etc.
  noValidate: true,
  schema: {
    properties: {
      content: { type: 'string' }
    }
  }
});
store.createRecord('user', { age: 'bar' }); // error is thrown

const user = store.createRecord('user', { age: 30 });
user.age = 'foo'; // error is thrown

store.createRecord('post', { title: 123 }); // error is thrown

const post = store.createRecord('post', { title: 'test' }); // error is NOT thrown
post.title = 1234; // error is NOT thrown

const comment = store.createRecord('comment', { content: 123 }); // error is NOT thrown
comment.content = 1234; // error is NOT thrown
```

**Comment by jmdobry** [comment]
I've also written http://www.js-data.io/v3.0/docs/validation. If you have further suggestions for that page (which still has some TODOs), please click the "Suggest Edits" button on the top right corner of that page.
