### ISSUE TITLE
r.js optimze does not seem to work

### ISSUE THREAD

**Issue by jbadeau** [js-data/js-data#40]
Hi,

data-js does not seem to optimze correctly with any version of r.js. The error is "Error: js-data must be loaded!". Have you tested with r.js?

Cheers,
Jose

**Comment by jmdobry** [comment]
I have not tried it with require.js. If you have suggestions on how to get js-data to work in the browser with browserify/webpack/requirejs and also on NodeJS, that would be greatly appreciated.

**Comment by jbadeau** [comment]
Ok I will have a look.

1. I think in the end it's prob better to offer a standalone build (js-data + dependencies) and a js-data only builds. This is so users can update their versions of dependencies (polymer observe, es6 promise shim)

2. i will investigate the browserify + amd issue but I suspect a solution like this (http://bl.ocks.org/nicolashery/9684078) is in order. I will make a pull request proposal for a build that works in your required runtimes (commonsjs, amd, global, browserify, etc)

Cheers,
Jose

**Comment by jmdobry** [comment]
The obverse-js polyfill is not upgradeable unless I do it. The version included with js-data has been heavily stripped down so as to avoid bundling unused code.

I have been considering switching the build to use webpack. I hear that it has very good support for doing this kind of thing.

I've also been thinking about authoring in ES6 and using 6to5 for the build. Not sure yet.

**Comment by jmdobry** [comment]
Closing because I think this has been fixed by switching to webpack and using UMD properly. Just point your r.js config to `dist/js-data.js` and it should work with AMD. See [the commit](https://github.com/js-data/js-data/commit/4f4bb0927e104c57df2e367887b54043adfa111d).

The js-data webpack config specifies some externals, and you might have to do the same in your r.js config. See [the config](https://github.com/js-data/js-data/blob/master/Gruntfile.js#L66) in the Gruntfile.

**Comment by jbadeau** [comment]
I can confirm that the r.js building works. :) thanx very much.
