### ISSUE TITLE
`get` properties break record merging

### ISSUE THREAD

**Issue by altschuler** [js-data/js-data#428]
In `Collection#add` when `onConflict === 'merge'` the `utils.deepMixin` is called on records, but when a record has a property with only getter it breaks.

**Comment by jmdobry** [comment]
Can you describe a case where a record has a property with only a getter?

**Comment by altschuler** [comment]
For instance:

```ts
export class Person extends Record {

    age: number;

    get isAdult() { return this.age > 18 }
}
```

**Comment by jmdobry** [comment]
Are you using TypeScript?

**Comment by altschuler** [comment]
Yes. It should be noted that I simply changed it from a getter to a regular method as a workaround.

**Comment by jmdobry** [comment]
You ran into this issue because of the way TypeScript compiles ES2015 classes to ES5. According to the ES2015 spec, your getter property should be non-enumerable, but TypeScript produces an enumerable property, hence why it is seen by `utils.deepMixIn` as it iterates over properties of the record.

You can change it to a method, as you mentioned, or you could add a setter that does nothing, or you can modify it to be non-enumerable.

Option 1:

```js
export class Person extends Record {
  age: number;
  isAdult () { return this.age > 18 }
}
```

Option 2:

```js
export class Person extends Record {
  age: number;
  get isAdult () { return this.age > 18 }
  set isAdult () {}
}
```

Option 3:

```js
export class Person extends Record {
  age: number;
  get isAdult () { return this.age > 18 }
}
Object.defineProperty(
  Person.prototype,
  Object.assign(
    Object.getOwnPropertyDescriptor(Person.prototype, 'isAdult'),
    {
      enumerable: false
    }
  )
)
```

**Comment by altschuler** [comment]
Great! Very informative, thank you very much! And thank you very, very much for `js-data`! :)
