### ISSUE TITLE
[Question] How to use WebSocket to update data in DataStore

### ISSUE THREAD

**Issue by reppners** [js-data/js-data#44]
How would one proceed if data is received via a WebSocket connection and then should be injected/updated/ejected in the DataStore? The inject/eject seams to be clear sailing because the API is there. But how should an existing item in the DataStore be updated via the synchronous API?

My first intention was to retrieve the item via get(), update it with the data received from the server and then save() it with some Noop-Adapter to get the data updated in the DataStore. Or am I overcomplicating things because just by editing the item it will be updated in the DataStore? Sry for this noob question but I'm just starting out with angular-data/js-data and have setup a small project to test a few things.

Are there any plans to support some kind of plugin/addon for js-data that goes in this direction of using WebSockets to get updates "automagically"?

**Comment by jmdobry** [comment]
> But how should an existing item in the DataStore be updated via the synchronous API?

Use `DS#inject`. If the item is already in the store than what you're injecting will be merged with the existing item. It's the perfect way to update what's in the data store.

Here's an example of how I do this in one of my apps:

```js
angular.module('app').service('Msg', function ($rootScope, DS) {
  'use strict';

  var socket = io.connect(app.url, { path: '/api/socket.io' });

  socket.on('create', function (data) {
    if (data.ownerId && $rootScope.loggedInUser && $rootScope.loggedInUser.id === data.ownerId) {
      DS.find(data.resource, data.id);
    }
    $rootScope.$broadcast('create', data.resource, data.id, data.ownerId);
  });

  // I don't send the actual item up the socket, just the id and resource name
  socket.on('update', function (data) {
    // Get the latest copy of the item if it's in the store
    DS.refresh(data.resource, data.id);
    $rootScope.$broadcast('update', data.resource, data.id, data.ownerId);
  });

  // This relates to your example (full payload sent up the socket)
  socket.on('update_full', function (data) {
    // Inject the data, updating any existing items
    DS.inject(data.resource, data.payload);
    $rootScope.$broadcast('update_full', data.resource, data.payload);
  });

  socket.on('destroy', function (data) {
    DS.eject(data.resource, data.id);
    $rootScope.$broadcast('destroy', data.resource, data.id, data.ownerId);
  });

  return {};
});
```

----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.io/org/groupsio/jsdata).

**Comment by reppners** [comment]
Super easy as I expected :) Thanks :)

**Comment by jmdobry** [comment]
:)
