### ISSUE TITLE
Second, identical findAll always returns an empty array

### ISSUE THREAD

**Issue by johman10** [js-data/js-data#448]
Great project! We as a team are enjoying to work with this.

## Description
For us there seems to be a small problem though. The first request goes fine and returns the right response. The second request, with the exact same parameters, however seems to return an array instead of the actual previous request. I'm expecting that this is a cache issue since doing.

I hope you can help us find the cause of this issue.

## What I already tried
- Run `clear()` before the findAll - fixes the issue but no caching :(
- Remove the deserializer from the model - didn't help at all, same problem

## Related code
_package.json_
```json
{
  "js-data": "^3.0.0-rc.9",
  "js-data-http": "~3.0.0-rc.2"
}
```

_store.js_
```js
import { DataStore } from 'js-data';
import { HttpAdapter } from 'js-data-http';
const store = new DataStore();

// Instantiate the HttpAdapter
const adapter = new HttpAdapter({
  basePath: '/v1'
});

// Register the adapter with the Mapper
store.registerAdapter('http', adapter, { 'default': true });

export default store;
```

_user.js_
```js
import store from './store';

store.defineMapper('User', {
  endpoint: '/users',
  deserialize (resourceConfig, response) {
    return response.data.user || response.data.users;
  },
  methods: {
    fullName () {
      return this.firstname + ' ' + this.surname;
    }
  }
});
const User = store.as('User');

export default User;
```

_findAll request_
```js
import User from 'models/user';
let users;
let meta;

// params.query is a dynamic string based on an search input
let params = {
  per_page: 20,
  page: 1,
  query: null
};

User.findAll(params, { raw: true })
  .then((response) => {
    meta = JSON.parse(response.request.response).meta;
    users = response.data;
  })
  .catch((error) => {
    console.error(error);
  });
```

**Comment by jmdobry** [comment]
Instead of `User.findAll(...)`, try this `store.getMapper('user').findAll(...)`.

Note, by calling the Mapper's `findAll` method, you're bypassing the store's caching functionality, so you'll need to manually add the records to the store after you receive them, e.g. `store.add('user', response.data)`

Also, I just wrote some detailed information on how caching works with the store's `find` and `findAll` methods: http://www.js-data.io/v3.0/docs/working-with-the-datastore#section-caching-queries

**Comment by esase** [comment]
@jmdobry I get the same result (empty array)

I left comment here - https://github.com/js-data/js-data/issues/451

>  I also found a bug:
> I get all items like this: this.api.findAll('users', {status: 'active});
> and it works only once!
> If you will try to call it again: this.api.findAll('users', {status: 'active}); you will get empty array. There is no cached items and it doesn't load data again from adapter. Just gets an empty array

**Comment by bbthorntz** [comment]
@jmdobry once again, great work!

Although I think understand why this happens, I too have been caught out by this and worried other developers will too as I believe the behaviour to be unintuitive for remote endpoints where the filtering, pagination and sorting has already been applied.

Assuming we're working with something like JSON-Server, how would we cache the following query?

```javascript
const query = {
    q: 'example',
    _page: 1,
    _limit: 10
};
store.findAll('posts', query); // http://localhost/posts/?_page=1&_limit=10&q=example
.then((records) => {}) // { id: 1, title: 'example 1', id: 2, title: 'example 2' }
```

This fails the second time because js-data attempts to filter the cache using the `query` parameters. Is there a way to say "hey, don't apply the query, just give me the exact data you received last time"?

**Comment by johman10** [comment]
@bbthorntz: I think this is something that JSData should do by itself right? In my mind it doesn't make a whole lot of sense that it suddenly returns an empty array because of cache. If JSData finds a cached response it should return the cached data, not an empty array.

For me in the specific situation described in the issue I was able to use `force: true`. But I can imagine how this is not always a valid scenario.

**Comment by jmdobry** [comment]
"intuitive" is just another word for "familiar". What is familiar to someone in one context, may not be familiar to others in the same or any other context. JSData's `DataStore` class is very complex and is built on top of layers of other components which are complex in their own right, so I struggle to see how anything about the `DataStore` class could really be familiar/intuitive to anyone, because I've never encountered another JavaScript component quite like it. In my mind, one would have to thoroughly read the `DataStore` component's documentation to build any familiarity or intuition as to what's going on under the hood.

The `Mapper` class on the other hand is simple: call `Mapper#findAll()`, once, twice, three times...you get the same result every time.

Aside note: The comments here and on #451 are the exact opposite of the complaints that I received against the default behavior of JSData v2, which was the opposite of the default behavior of v3. Basically, there's a set of people who are underrepresented in these two issues, and it's those for whom the current behavior _is_ familiar (or intuitive or whatever).

### My recommendation

The default behavior and options for the `DataStore` class were chosen with these guidelines in mind:

1. When you need to load a subset of records from your database into the datastore, call `DataStore#find()` or `DataStore#findAll()`.
2. When you need to load a subset of records from the datastore into your View, call `DataStore#get()` or `DataStore#filter()`.

If you do not want to deal with that distinction, just use `Mapper#findAll()` (e.g. `store.getMapper('comment').findAll(...)`), and manually insert records into the store if you want. [Here's an example](https://github.com/js-data/js-data-examples/blob/master/client/angular1/src/posts.js#L10)

**Comment by prionkor** [comment]
Using `dataStore.getMapper('comment').findAll({...})` sends ajax request every time. So, it beats the purpose of the caching.

**Comment by jmdobry** [comment]
@prionkor Mappers do not implement any caching whatsoever. Caching is implemented by the `SimpleStore` and `DataStore` classes.

> Using `store.getMapper('comment').findAll({...})` sends ajax request (or connects to db) every time. So, it beats the purpose of the caching.

Exactly, `store.getMapper('comment').findAll({...})` is how you explicitly bypass the caching implemented by the store. `store.findAll('comment', {...})` will activate automatic caching.

**Comment by jmdobry** [comment]
I'm going to consider this resolved, per my answer [here](https://github.com/js-data/js-data/issues/448#issuecomment-287522472)

**Comment by brodie-g** [comment]
I encountered this too - second requests, with query params, returned an empty array. After some debugging, I tracked the issue down to the default `SimpleStore.cacheFindAll()` function:
```
cacheFindAll (name, data, hash, opts) {
    this._completedQueries[name][hash] = (name, hash, opts) => this.filter(name, utils.fromJson(hash))
 },
```

I believe what happens is, when the store comes to a cached record, by default, it will dive in and do some local filtering based on the query params, not return the straight result as if making the HTTP call.

What worked for me was to override `cacheFindAll` with:
```
  cacheFindAll (name, data, hash, opts) {
    this._completedQueries[name][hash] = data;
  }
```
setting the cache to the exact data.
Hopefully my understanding of this is correct, but this solution seemed to work for me.

**Comment by johman10** [comment]
@brodie-g's approach is actually quite nice. I ended up doing something similar in my project. To add up onto that you might have issues with cache if you have a SPA running though, since removing records won't actually works.

So to add up onto that solution we did this:
```js
import { DataStore } from 'js-data';
import { HttpAdapter } from 'js-data-http';

function setCache (store, mapperName, data, queryHashOrId) {
  return store._completedQueries[mapperName][queryHashOrId] = data;
}

function removeCache (store, mapperName) {
  if (!store._completedQueries) return;
  store._completedQueries[mapperName] = {};
}

// Override the cache methods from the DataStore to just save the plain objects instead of functions.
const store = new DataStore({
  cacheFindAll (mapperName, data, queryHash) {
    return setCache(this, mapperName, data, queryHash);
  },
  cacheFind (mapperName, data, id) {
    return setCache(this, mapperName, data, id);
  }
});

// Invalidate the cache of a mapper as soon as one or more records is changed to make sure a new request will be made to the HTTP server
const adapter = new HttpAdapter({
  afterCreate (mapper) {
    return removeCache(store, mapper.name);
  },
  afterCreateMany (mapper) {
    return removeCache(store, mapper.name);
  },
  afterDestroy (mapper) {
    return removeCache(store, mapper.name);
  },
  afterDestroyAll (mapper) {
    return removeCache(store, mapper.name);
  },
  afterUpdate (mapper) {
    return removeCache(store, mapper.name);
  },
  afterUpdateAll (mapper) {
    return removeCache(store, mapper.name);
  },
  afterUpdateMany (mapper) {
    return removeCache(store, mapper.name);
  },
  http: httpForAdapter
});
```

We are running this in a production app without any problems by now. Personally I'm all happy with this solution. :D
