### ISSUE TITLE
custom instance methods using es6 classes

### ISSUE THREAD

**Issue by pietschy** [js-data/js-data#45]
Hi there, 

I'm using es6 in my current project and would like to have my DS models extend some existing base classes.  I've been googling but I can't think of a nice way to give js-data the  `methods: { ... }`  and use those in my classes (again, not a JS expert).  It might be possible to mix methods: {..} into my class using Object.assign(..) but that feels kinda wrong.

Do have any thoughts on this?

Thanks & cheers

**Comment by jmdobry** [comment]
The `methods` option is just a plain object, whose keys are names and values are functions. When the resource is defined, `methods` is mixed into the `prototype` of the instance constructor function that will be used by the new resource when it creates instances. ES6 classes put the methods onto the prototype as well. Since you want to write in ES6, I'm thinking you need to define your classes first and then mix the resulting prototype methods into the `methods` object. You probably don't want to blindly pull everything from the class prototype, but pick the ones you want.

Something like this:

```js
class Foo {
  constructor() {
    this.foo = 'bar';
  }
  baz() {
  }
  boo() {
    console.log(this.foo);
  }
}
```

```js
var foo = new Foo();
foo.boo(); // "bar"

var Bar = DS.defineResource({
  name: 'Bar',
  methods: DS.utils.pick(Foo.prototype, ['baz', 'boo'])
});

var bar = Bar.createInstance({
  foo: 'baz'
});

bar.boo(); // "baz"
```

Let me know how it works out for you.

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.io/org/groupsio/jsdata).

**Comment by pietschy** [comment]
Excellent, I'll give that a go.  Thanks.
