### ISSUE TITLE
store.clear() doesn't exist?

### ISSUE THREAD

**Issue by jredd** [js-data/js-data#458]
"js-data": "^3.0.0-rc.9",
"js-data-http": "^3.0.0-rc.2",

I need to clear all the cached store when users log out of the system and I was looking at the documentation for this and came across store.clear() in the Working with the DataStore section of the documentation. When I try and use it though TS wont compile

Property 'clear' does not exist on type 'DataStore'

Am I missing something here?

**Comment by kvandelden** [comment]
This relates to issue 444, the d.ts is out of sync.
The clear function is in the SimpleStore class..

![image](https://cloud.githubusercontent.com/assets/17126950/25156151/83a3c304-245e-11e7-98d3-c43ada87a5f8.png)

The inheritance structure looks like DataStore extends SimpleStore extends Container..
![image](https://cloud.githubusercontent.com/assets/17126950/25156403/de51a8d8-245f-11e7-908a-e729ec73c630.png)

![image](https://cloud.githubusercontent.com/assets/17126950/25156410/ed6ee24a-245f-11e7-9163-d315feaaae81.png)


The d.ts file shows  DataStore extends Container.  If that is intentional, then the SimpleStore methods would need to be added to the DataStore class.
![image](https://cloud.githubusercontent.com/assets/17126950/25156438/2e2d9f2e-2460-11e7-9a4f-81f54c1e509c.png)
