### ISSUE TITLE
Change Tracking: property change call back..

### ISSUE THREAD

**Issue by kvandelden** [js-data/js-data#476]
--- (see second comment for resolution to initial issue)

I've setup multiple column level event handlers on a record...
      change:Col1   , change:Col2,...

The handlers get fired, however, the handlers are fired too frequently when a change hasn't occurred since the first change.

    If the changes are made in order:
         Change to Col1:     Col1 handler is fired.
         Change to Col2:     Col1 & Col2 handler are fired.
         Change to Col3:     Col1, Col2 & Col 3 handler are fired.

This is fairly minor, but the behavior has a negative impact on how the handler's can be utilized to detect concise changes.

Schema.js line 911 , in the property setter, iterates over all record changes.. and does the emits.
     
![image](https://user-images.githubusercontent.com/17126950/29237243-faf98e4e-7edf-11e7-9801-05f22dd22a54.png)

The (prop) parameter could be used to limit the emitted change to the single column.
 

Thanks,
Kurt

**Comment by kvandelden** [comment]
It appears I am observing the debounding behavior of the change event.   Changes are batched up in the setter..  
   Just a note...   In the setTimeout callback, I see the use of "this", which may be invalid during the call back.?

Thanks,
Kurt

**Comment by jmdobry** [comment]
The use of `this` is valid because it's being used inside a ES5 property setter, which is always invoked with the context of the object on which the property is being set.

The change detection merges changes to a single property that happen within a single turn of the event loop into one change event. This is part of the force asynchronicity of JSData's change detection. Yes, you may lose some precision on the changes. If you want to capture more precise changes, you can subclass `Schema` and override the `makeDescriptor` method (as of v3.0.1), or add your own property getters/setters to your `Record` classes.

**Comment by kvandelden** [comment]
Perfect.. that helps a lot.
   
    We appreciate all your help and continue to be very impressed with quality of work put into js-data.  We build better products when leveraging js-data.

Thanks, Kurt

**Comment by jmdobry** [comment]
Thanks! I'm happy it's serving you well.
