### ISSUE TITLE
[v3] Relations where the local key is a nested property do not work when dynamically updated

### ISSUE THREAD

**Issue by mattlewis92** [js-data/js-data#479]
## Description
Any relations where the local key is a nested property are not updated when that property is changed. I guess this is because of the user of setters to detect when the property is changed and these are only applied to top level properties. This used to work ok in v2 though.

If you have any pointers off the top of your head on how to fix this I'd be happy to make a PR 😄 

## Steps to reproduce
See this plunker: http://plnkr.co/edit/pOmrYD80gXc2spprUtb0?p=preview

p.s. thanks for the great work on v3, I've just upgraded our app to it today and this is the only thing that bit me, everything else was smooth! 😄

**Comment by jmdobry** [comment]
The main issue here is that v3 change detection model is active, leveraging ES5 setters. v2's change detection used the now deprecated `Object.observe`, which was a slow, asynchronous deep dirty check.

I myself have attempted twice to implement change detection on nested properties in v3, and both times the complexity was too extreme and I gave up. The problem is that you need subclasses to represent the nested objects, and those subclasses need the ES5 setters as well.

**Comment by mattlewis92** [comment]
Ah right, I can see how that would be a problem. I've worked around this by re-adding the record to the store when I know the relationship key has changed which forces the relationships to update. It's hacky but it works 🤷‍♂️
