### ISSUE TITLE
how good is that ? trying to understand filter performance

### ISSUE THREAD

**Issue by sallespro** [js-data/js-data#61]
is there a faster query mecanism to select records within a range of attributes ?
```
		var params = {
  			where: {
      			age: {
       				 '>': 10,
        			'<': 30 
        			}
        		}
			};
```
results 
```
null 'new data store created' {} null null
48 records/seconds [1000] records created >> in 20.679 seconds
18 records/second [382] records out of 1000 >> in 20.689 seconds

null 'new data store created' {} null null
8 records/seconds [5000] records created >> in 556.671 seconds
3 records/second [1902] records out of 5000 >> in 556.697 seconds
```

**Comment by jmdobry** [comment]
Sure,

```js
var profiles = Profile.getAll();
profiles = profiles.filter(function (profile) {
  return profile.age > 10 && profile.age < 30;
});
```

or for better browser compatibility:

```js
var profiles = Profile.getAll();
profiles = store.utils.filter(profiles, function (profile) {
  return profile.age > 10 && profile.age < 30;
});
```

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.io/org/groupsio/jsdata).
