### ISSUE TITLE
"saved" and "lastSaved" method seems to be a misnomer

### ISSUE THREAD

**Issue by dremonkey** [js-data/js-data#66]
I'm trying to understand your logic behind the "saved" flag here https://github.com/js-data/js-data/blob/master/src/datastore/sync_methods/inject.js#L178 and the ```DS#lastSaved``` method. The documentation states that this is the last time the resource item was saved using an adapter, but this is not true if you call DS#inject directly (which I am doing to add a new item to a resource collection prior to it needing to be saved). So my question is what was the login behind putting the flag in inject rather than the methods that actually utilize the adapter (DS#create, DS#update, DS#save, DS#find, etc)? And would it make more sense to move it to the async methods that utilize the adapter?

**Comment by jmdobry** [comment]
I believe I did it that way because each of those methods calls `DS#inject` internally, so instead of writing the same code in six places I just put it in one place. Based on what you're doing, I can see why it might be a misnomer. I guess from the point of view of the data store, it's trying to track "when is the last time I received a fresh copy of this item?". With the current implementation, the data store doesn't know the difference between an item injected manually, and an item injected as a result of `find`, `update`, etc. 

I could create a clearer definition of what `lastSaved` means, and fix the code to match, or split `lastSaved` in to `lastSaved` and `lastInjected`, increasing the amount of meta data stored by the data store a not insignificant amount. 

What are the ways you use or might use the `lastSaved` meta data? I haven't gotten any feedback on that feature before.

**Comment by dremonkey** [comment]
Wouldn't it be possible to make the distinction between ```lastSaved``` and ```lastInjected``` using the already two existing meta properties ```lastSaved``` and ```lastUpdated``` rather than needing to add a third property? From what I can tell there seems to be very little difference between ```lastSaved``` and ```lastModified```

So ```lastSaved``` would be strictly for keeping track of when the adapter was actually used (i.e. this is the last time the data was synced with the database), while ```lastUpdated``` would change every time the model data changes (both via sync method like ```#set ``` and an async method like ```#find```

My use case is basically as follows:

1. User creates a new annotation (```#createInstance``` and ```#inject```) but **unsaved** - update ```lastUpdated``
2. User modifies that annotation (```#set```)... still **unsaved** -  update ```lastUpdated```
3. User has a decision to make:
- 3a. Save the annotation (```#create```)... now **saved** so update ```lastSaved``` and ```lastUpdated```
- 3b. Not save the annotation
4. User doesn't want the annotation  anymore. So at this point we have a choice depending on what the user did on step 3. Either use ```#eject``` if the annotation is unsaved or ```#destroy``` if the annotation is saved. Essentially I want to use the ```lastSaved``` information to determine which method to use.

**Comment by jmdobry** [comment]
> very little difference

One major difference between `lastModified` and `lastSaved` is that `lastModified` is automatically be updated even when you do something like `user.name = 'John'` because of js-data's use of `Object.observe`.

Regarding your use case, you're creating a fake primary key for the annotation in order to inject it into the store right? My approach thus far has been to use `#createInstance` but _not_ inject the unsaved item into the store. My controller or whatever holds on to that unsaved instance, and if the user wants to keep it then I call `#create` straight away, which then injects the saved instance into the store. I imagine your approach comes from a desire to maintain that unsaved instance even if the has has navigated to some other part of your app. I can see how one would want to be able to use the data store to manage unsaved (uncreated) instances.

Just because an item gets injected, the data store shouldn't assume that the item has been saved. If we only set `lastSaved` when the async methods run, then I think that will satisfy these use cases. Agree?

**Comment by dremonkey** [comment]
My thoughts exactly. Would you like to make the changes yourself or would you prefer I make the changes, update the tests, and make a pull request?

**Comment by jmdobry** [comment]
I'll do it.

**Comment by dremonkey** [comment]
cool
