### ISSUE TITLE
Planning 2.0

### ISSUE THREAD

**Issue by jmdobry** [js-data/js-data#68]
Thanks to the feedback coming in, there are some improvements that may necessitate breaking changes. Hence the 2.0. 

Ideas/Issues:

### Dependencies
#121 Remove the bundled Promise polyfill. In 2.0 js-data will expect there to be a global `Promise` constructor.

#122 Remove js-data-schema-specific code from js-data. Js-data already provides the necessary lifecycle hooks where you can do whatever validation you want using whatever library you want.

### Change Tracking
I'm not sure it's as intelligent as it could be. Some change tracking features affect performance, and cannot be disabled. They need to be more configurable. The general use case may be that some need to be disabled by default.

### Events/Lifecycle Hooks
There are multiple actions umbrella'd under the `notify` option. They should be split up.

### Plugin architecture
Things are maybe a little too coupled right now. If js-data could move closer to a plugin architecture, various modules could be swapped out to modify behavior according to varying needs. e.g. change detection as a feature could be a plugin, that can be removed/added/swapped for something else. 

There should be a clearer separation between data store and async operation stuff. Perhaps the code could be split into smaller modules. Maybe js-data-store.js & js-data-async.js, with js-data.js being the combination of the two. js-data-store.js would be the store, synchronous methods, change detection. js-data-async.js would have the find, findAll, etc. and delegate to adapters.

### Url building
url building in js-data is still rather primitive. With a plugin architecture, this feature could be improved without coupling other non-http-related pieces of js-data to http-related activities. Actions are a little too simple right now as well. 

### Relations
Many use cases are proving more advanced than js-data's capabilities. Need improvements here.

#107 - Relation linking using property accessors

### Immutable data
Could js-data have an "immutable data" mode? (React/Flux) With a plugin system, perhaps this would be possible.

### Gathering feedback
I _really_ wish there was an easy way to gather usage data. Which features are heavily used and should be given more attention/optimization? Which features are hardly used and should be removed?

### Offline/Sync
What could be done to make js-data smart enough for an automatic offline/online storage and re-sync capability?

### Other
- some micro-optimizations are unnecessary and should be undone

Please comment.

**Comment by diwu1989** [comment]
higher unit test coverage

**Comment by goldcaddy77** [comment]
What about adding some of the DS methods directly on the resource instance.  `save` in particular.  Right now, in order to save a model, I need to do something like:

**Controller**
```
angular.module('dx')
.controller( 'CampaignEditController', function( $scope, resolvedCampaign, Campaign ){
  $scope.campaign = resolvedCampaign;
  $scope.$save = function() {
    Campaign.save(resolvedCampaign.uid);
  };
});
```

**HTML**
```
  <form ng-submit="save()">
    <input ng-model="campaign.name">
    <input type="submit">
  </form>
```

I'd love to be able to do:

**HTML**
```
  <form ng-submit="campaign.$save()">
    <input ng-model="campaign.name">
    <input type="submit">
  </form>
```

I would also love the errors object to be exposed that way so that you can bind to `campaign.$errors.name` directly in your templates.

This is what I liked about the ngActiveResource project most:  https://github.com/FacultyCreative/ngActiveResource#simple

**Comment by jmdobry** [comment]
@goldcaddy77 They have already been added, they're just named slightly different on the instances so as not to clash with anything you might put in the `methods` option. 

**Controller**
```
angular.module('dx')
.controller( 'CampaignEditController', function( $scope, resolvedCampaign, Campaign ){
  $scope.campaign = resolvedCampaign;
});
```

**HTML**
```
  <form ng-submit="campaign.DSSave()">
    <input ng-model="campaign.name">
    <input type="submit">
  </form>
```

See [DS#save](http://www.js-data.io/docs/dssave#examples).

The downside I see to calling the instance method directly in the template is that you're bypassing the C in MVC and going straight from V to M. If there's an error you haven't attached any `.catch` handler in order react to the error. I don't particularly like the idea of attaching the errors directly to the instance. The point of MVC is that the Controller reacts to what happens in the View (e.g. ngSubmit), does necessary business domain logic through the Model, then shuffles data back to the View.

**Comment by goldcaddy77** [comment]
Sorry went on vacation shortly after my last post.  I understand the concern with going straight from V to M, but the controller has already done it's work.  It has set up the view model by attaching the model to $scope.  What you get by having the `$errors` property directly on the model is being able to show error messages by looking at `$scope.campaign.errors.name` like:  https://github.com/FacultyCreative/ngActiveResource#usage-in-forms

How would you recommend doing this otherwise?  In the project I just completed, having the errors object as a first class citizen on the object was very helpful.

**Comment by jmdobry** [comment]
One of the driving philosophies of js-data is that is not modify your data (with the exception of computed properties and relations which are optional, and are defined by you), so the idea of taking errors of arbitrary formats from arbitrary sources and attaching this stuff to your data runs contrary to this opinion. Js-data is a Model library, and thus has zero concern for the View. Attaching "own" error properties to objects would also mess with change detection, reporting errors as changes. For those who use js-data-schema, they would have add error properties to their schemas. In order to even grab those errors js-data would need to add its own error handler to the promise chain. Yes, it can be done, but would require "shotgun" changes to js-data, with a lot of `if` statements. I try to generalize js-data for as many use cases as reasonable, but some do not make the cut. I do not want to bloat the library, so it will remain focused on being an (opinionated) data library that reports results in the control flow of operations, without modifying your data. You are free however, to attach any errors objects to your data as you see fit.

**Comment by goldcaddy77** [comment]
Cool, this definitely makes sense. :+1:  I suppose something like this makes more sense in js-data-angular or a wrapper for js-data that is Angular-centric.  I'll keep future recommendations to be independent.

**Comment by demisx** [comment]
Will be cool if JS-Data could match http://bookshelfjs.org/ features, so we could use it on the server side too. Can't use it on the server without support for migrations, transactions and other. Not sure if this is relevant to 2.0 scope, though.

**Comment by jmdobry** [comment]
No it's relevant. While js-data does work on the server, it will be limited somewhat by how well it could support migrations, transactions, etc. Each database/persistence layer has its own capabilities. BookshelfJS uses the Knex.js sql query builder, which is also used by the js-data-sql adapter, so perhaps the issue of migrations, transactions, etc. support for sql databases would need to be addressed in the js-data-sql adapter.

Other adapters work with databases that don't have such a thing as transactions, so it may be that each adapter needs to address it separately, independent of js-data 2.0.

**Comment by demisx** [comment]
@jmdobry Yes, that makes sense. The beauty of JS-Data is that is strives to be persistent layer agnostic and it should remain that way. 

What about `belongsToMany` (and maybe even `polymorphic`) relations? Can those be considered for 2.0?

**Comment by jmdobry** [comment]
Can you describe `belongsToMany`? How is that different from having multiple `belongsTo` relationships?

**Comment by demisx** [comment]
I guess `belongsToMany` would be more of a convenience relation in `many-to-many` relationship, that would take care of setting up the join model for you. Similar to http://bookshelfjs.org/#Model-belongsToMany.

**Comment by jmdobry** [comment]
Question to all:

In 2.0, relation links will be handled by property accessors added to the prototype of instance constructors. They will not be enumerable by default. Even if you do set them to be enumerable, they won't be "own" properties of items. I'd like to reduce complexity and the amount of edge cases I have to consider by removing unecessary/seldom used features, etc. So, here are some questions about usage:

- Do you ever set the `useClass` option to `false`? Why or why not? If you've never set it to `false`, please say so. I'm considering disallowing `false` as a possible value for `useClass`.
- Non-enumerable relation links in 2.0 means that if you `console.log` an item, its relations won't show up (though you can still access them directly with the dot "." operator). Do you care? Why or why not?

**Comment by demisx** [comment]
> Do you ever set the useClass option to false? Why or why not? If you've never set it to false, please say so. I'm considering disallowing false as a possible value for useClass.
Never set it to false. 

> Non-enumerable relation links in 2.0 means that if you console.log an item, its relations won't show up (though you can still access them directly with the dot "." operator). Do you care? Why or why not
Don't see any issue with that as long as we can access relations via a method call or a '.'

**Comment by rmja** [comment]
I also never use useClass and property accessors is the future😊 I have had several problems with the current link approach, because the links were not always up to date. One question though, how well does accessors work together with data binding using e.g. angular? Does it just work as expected, without too much hassle?

**Comment by jmdobry** [comment]
With the accessors the relations will always be up to date with what is in the store.

**Comment by WillsB3** [comment]
We're using js-data in a large Angular app, and for some of the models we have we have some quite specific filtering requirements. For example you can filter items by distance (each model has a lat/lng field) from a given location. This is more difficult on the client side than on the server as this sort of filtering is supported automatically with our database. 

We have a list page which lists these models (100 or 200 at a time for instance) with filtering controls that allow the user to specify multiple filters and change the sort order. Because of the complex filtering that can't be handled entirely on the frontend we rely on the backend to provide the data to populate this list page. To do this we came up with a sort of hacked `Collection` class that kind of works like Backbone's `Collection` class. Whenever a filter is changed on the front-end we build up the request parameters from filters and perform a manual fetch to the backend for an updated set of results. However, because of this we loose out on most of js-data's usefulness. For example, while we could set a cache timeout for this type of model it would cause problems with our collection logic. E.G. What if one of our Collections had a reference to a model which has since been ejected from the cache for instance, this would likely cause issues...

I'm not 100% clear on what sort of thing js-data could offer for this sort of backend-driven filtering use-case, but I wonder if there is some scope for some sort of more advanced collection logic within js-data. Currently angular-js-data offers a some sort of pseudo collection via `bindAll` in that you can grab a reference to a subset of models in the store that match a given set of filtering conditions using the [where syntax](http://www.js-data.io/v1.8.0/docs/query-syntax) but as stated that isn't very helpful if your filter cannot be applied using the query syntax. I'm aware that we can manually add in custom query syntax but as previously discussed we aren't always able to do all the filtering on the frontend and so have to rely on the Backend for some filtering of some models. 

Would some sort of `Collection` class, perhaps with it's own built in caching layer be a sensible addition to js-data? Do you think it's feasible? How could it fit in with how js-data currently works?

**Comment by WillsB3** [comment]
Also, +1 for more flexible URL building logic. See https://github.com/js-data/js-data/issues/116.

**Comment by wordofchristian** [comment]
Any plans for adding an adapter or support for the http://jsonapi.org/ spec.

**Comment by jmdobry** [comment]
None from me personally, but if someone in the community wants to work on it, I'm more than happy to provide support.

**Comment by pdemilly** [comment]
Any plans on supporting realtime asynchronous update of the data store from backend like firebase?

**Comment by jmdobry** [comment]
Thoughts yes, specific plans no.

**Comment by pdemilly** [comment]
Could be nice to have something like autoRefresh: ttl to a have a previous find query refreshed asynchronously and automatically and to have bind and bindAll functions for a firebase adapter resolve to a $firebaseObject or $firebaseArray but that would probably mean that the firebaseAdapter depends on angular

**Comment by internalfx** [comment]
@jmdobry I posted a chat on gitter before I saw this. You beat me to it on immutable data.

I would imagine there would be some performance gains to be had with a library like immutable.js

Especially for detecting changes.

**Comment by internalfx** [comment]
probably time to close this and open a new issue to carry items over
