### ISSUE TITLE
Using resource base class w/additional properties has some side effects

### ISSUE THREAD

**Issue by jessemorton** [js-data/js-data#69]
Using js-data v1.4.0, having a base class that has its own properties defined has side effects, such as throwing a false positive for DSHasChanges(). Example:

    var RESOURCE_NAME = 'shapeRectangle';

    function ShapeBase() {
        this.RESOURCE_TYPE = 'shape';
    }
    function ShapeRectangleClass() {
        this.DS_RESOURCE_NAME = RESOURCE_NAME;
    }

    ShapeRectangleClass.prototype = new ShapeBase();

    var ShapeRectangle = DS.defineResource({
        name: RESOURCE_NAME,
        endpoint: 'shapes',
        useClass: ShapesRectangleClass,
        ...
     });

Doing something like 

    ShapeRectangle.find(5).then(function(shapeRectangle) { 
        var hasChanges = shapeRectangle.DSHasChanges();
    })

results in `RESOURCE_TYPE` and `DS_RESOURCE_NAME` appearing in `hasChanges.added`

Related to #51

**Comment by jmdobry** [comment]
In your example, `RESOURCE_TYPE` and `DS_RESOURCE_NAME` are not properties inherited from the prototype chain, but are attached as "own" properties to the `shapeRectangle` instance. Therefore, they are treated just like any other values you would add/modify/remove on the `shapeRectangle` instance. 

The false positive is probably because of a different issue. I'll dig around some more.

**Comment by jmdobry** [comment]
Found it, the previous attributes are being recorded before the base class constructor runs. Will be fixed in 1.5.1.

**Comment by jessemorton** [comment]
With the modifications in 1.5.1, it takes care of the closest parent class's properties not appearing in `DSChanges()`, but other ancestors' properties still appear.

For example, in my code above, `ShapeBase` properties still 'unexpectedly' appear in `DSChanges()` even if not changed, while `ShapeRectangleClass` properties are correctly not considered changes:

    >>> shapeRectangle.DSChanges()
   
    {
        added: {
            RESOURCE_TYPE: 'shape'
        },
        changed: {},
        removed: {}
    }

Looking at my `shapeRectangle` object in the console, it's showing proto of `shapeRectangle` being `Ctor`, and the proto of `Ctor` being `ShapeBase`. If I'm understanding it correctly, that's maybe the same issue as what you've just fixed, but just moved up one level? Maybe my situation is a bit of an edge case to not worry about prioritizing currently, but thought I'd let you know anyway. Maybe I'll do a pull request if you're not keen on updating it.

**Comment by jmdobry** [comment]
Looking at the diffing method in observe-js, it doesn't differentiate between "own" properties and inherited properties. That's the issue, because when I track the "original" properties from which to diff changes, I don't save prototype properties. One or the other is going to need to change, or there will always be "changes" if you set any properties in your custom class constructor. Thoughts on which one?

**Comment by jessemorton** [comment]
:+1: Didn't get your question till this morning, but it's working well w/1.5.2.
