### ISSUE TITLE
Documentation seems to be down very often

### ISSUE THREAD

**Issue by reppners** [js-data/js-data#73]
Hey there, 

The last two weeks I was developing an application using js-data and making improvements to the type declarations for typescript and almost always when I hit the [documentation](http://www.js-data.io) the site is down. Is there anything that can be done about it or is it just me?

EDIT: Just now it is working again. 10 minutes ago it wasn't. But this behavior is the same every day for me. Is there some automatic rebuild of the docs and in the moment when they are updated they appear offline for a few minutes?

**Comment by jmdobry** [comment]
The docs are hosted at Readme.io. Since I put the docs there I have only seen one outage, and I view the docs several times a day. If I have visited the docs 1000 times,it's been up 999 times. Where are you in the world? And what do you see in the browser when it's down for you? Maybe you have some information I could forward to the Readme.io folks.

**Comment by reppners** [comment]
Then its really just me I guess. Strange..

I'm located in southern Germany. Working on OS X 10.10.2 with Safari 8.0.3 and Chrome 41.

If you have somebody I can turn to at Readme.io maybe I can provide them more detailed info if needed.

**Comment by jmdobry** [comment]
support@readme.io

**Comment by reppners** [comment]
Problem seems to have vanished :)
