### ISSUE TITLE
Default value for defined schema

### ISSUE THREAD

**Issue by facultymatt** [js-data/js-data#90]
Is if possible to set a default value when defining schema? For example:

```
var Order = DS.defineResource({
  name: 'order',
  endpoint: 'orders',
  idAttribute: '_id',
  schema: {
    status: {
      type: 'string',
      'default': 'NEW'
    }
  }
});

var order = Order.create({});

expect(order.status).toEqual('NEW) // true
```

I see the schema library supports defaults via `setDefaults` but was not able to get it working in the content of defining a resource.

**Comment by jmdobry** [comment]
You can call `setDefaults` immediately after defining your resource.

```js
var Order = DS.defineResource({
  //...
  // do something like this somewhere, doesn't have to be here
  afterCreateInstance: function(resource, attrs) {
    Order.schema.addDefaultsToTarget(attrs);
  },
  // ...
});
Order.schema.setDefaults({...});
```

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.io/org/groupsio/jsdata).

**Comment by facultymatt** [comment]
I agree this issue is not really a bug (more of a documentation need) so will leave closed.

I tried implementing what you suggested and I did not work.

I believe this is because of a set of bugs related to how lifecycle methods are handled. I did some investigation and according to the documentation the `afterCreateInstance` event is called with 2 variables: `resource` and `attrs`. The names are misleading and do not represent what is actually passed to the method. 

- resource: [the Options for this instance](https://github.com/js-data/js-data/blob/08ab3d404ace9d3f33316fdce189bc8059126c31/src/datastore/sync_methods/index.js#L123) Not the resource or instance. 

- attrs: [the original attributes as passed into the createInstance method.](https://github.com/js-data/js-data/blob/08ab3d404ace9d3f33316fdce189bc8059126c31/src/datastore/sync_methods/index.js#L115) Not the properties of the resource.

Additionally, you do not utilize `call` or `apply` on the method, so any changes made within the callback are not in the proper scope. They would need to treated as the compute method, for example. 

Either of the following changes to [this line](https://github.com/js-data/js-data/blob/08ab3d404ace9d3f33316fdce189bc8059126c31/src/datastore/sync_methods/index.js#L139) work: 

```
// change 1
options.afterCreateInstance(item, attrs);

// this method works
afterCreateInstance: function(resource, attrs) {
    Wheel.schema.addDefaultsToTarget(resource);
}
```

```
// change 2
options.afterCreateInstance.call(item, attrs);

// this method works
afterCreateInstance: function(attrs) {
    Wheel.schema.addDefaultsToTarget(this);
}
```

The same issue exists with other lifecycle methods, at least I spotted afterInject and beforeCreateInstance.

I would suggest this is opened as separate issue...

**Comment by jmdobry** [comment]
So `resource`, while when you log it to the console it prints `Options ...`, it is actually the `options` variable wrapped in a constructor function that uses the resource definition as its prototype, so thanks to prototypal inheritance, it _is_ the resource in essence. You can explore [this line](https://github.com/js-data/js-data/blob/master/src/datastore/sync_methods/index.js#L123) to see that this is true.

I will agree however, that I am passing the wrong second argument to `afterCreateInstance`. Instead of passing `attrs` I should be passing `item`, which is what is ultimately returned by the `createInstance` method. That right there is the bug, and [here](https://github.com/js-data/js-data/issues/91) is the issue for it.

Until I fix this bug, you'll just want to add defaults to items somewhere else, perhaps in the `afterInject` hook.
