### ISSUE TITLE
DS.get() throws exception on id=0

### ISSUE THREAD

**Issue by lillylykho** [js-data/js-data#99]
Hi,

I'm experiencing an issues where DS._inject() throws an exception with the following error:
"[ng:areq] Expected key to be a string! Found: number.

This only happens when injecting an object where the value of the id attribute is "0".

Is there any workaround for this?

Thanks

**Comment by jmdobry** [comment]
> [ng:areq] Expected key to be a string! Found: number.

This is an error thrown by Angular's internal ngMin helper service. _Angular_ expected a string and got a number. Here's [a plunker](http://plnkr.co/edit/UhME5n?p=preview) demonstrating that js-data can handle it when the id is `"0"`. It also works with `0`.

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.io/org/groupsio/jsdata).
